### ISSUE TITLE
Matterbridge crashes on WhatsApp PM

### ISSUE THREAD

**Issue by Dellle** [42wim/matterbridge#1180]
**Describe the bug**
Everytime I receive a private message in whatsapp, the matterbridge crashes.

**To Reproduce**
Configure matterbridge for Matrix and WhatsApp. 
Receive a message in a WhatsApp group => OK
Receive a message directly from a contact => crash

**Expected behavior**
I would expect, that the bridge does not crash when I receive a PM.
The PM does not need to be bridged to Matrix. 

**Screenshots/debug logs**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x156daa7]

goroutine 486 [running]:
github.com/42wim/matterbridge/bridge/whatsapp.(*Bwhatsapp).HandleTextMessage(0xc000342630, 0xc002bea0a0, 0x20, 0xc002bea080, 0x1c, 0x0, 0x0, 0x0, 0x5f142591, 0x0, ...)
	/go/src/github.com/42wim/matterbridge/bridge/whatsapp/handlers.go:81 +0xb7
created by github.com/Rhymen/go-whatsapp.(*Conn).handleWithCustomHandlers
	/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200421062035-31e8111ac334/handler.go:202 +0x16be
```

**Environment (please complete the following information):**
 - OS: official Docker container 42wim/matterbridge:stable
 - Matterbridge version: 1.17.5

**Additional context**
```
[matrix.mymatrix]
Server="https://m4tr1x.ems.host"

Login="<username>"
Password="<passwod>"

RemoteNickFormat="{NICK}: "

NoHomeServerSuffix=true

[whatsapp.mywhatsapp]
Number="+49xxxxxxxx"

SessionFile="/etc/matterbridge/session-49xxxxxxxx.gob"

QrOnWhiteTerminal=false

RemoteNickFormat=""

[[gateway]]
name="matrix-test"
enable=true

[[gateway.inout]]
account="matrix.mymatrix"
channel="#matrix-test:the.m4tr1x.chat"

[[gateway.inout]]
account="whatsapp.mywhatsapp"
channel="49xxxxxxxx-1595152434@g.us"
```

**Comment by 42wim** [comment]
Thanks for reporting, fixed in master

**Comment by nathanaelhoun** [comment]
Hi! This issue is still occuring to me, even after upgrading to [v1.18.1](https://github.com/42wim/matterbridge/releases/tag/v1.18.1)

Here are the logs:
```bash
[0000]  INFO main:         Running version 1.18.1 39f4fb34

// ...

[0006]  INFO main:         Gateway(s) started succesfully. Now relaying messages

// Receiving the Whatsapp private message
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16dad69]

goroutine 146 [running]:
github.com/42wim/matterbridge/bridge/whatsapp.(*Bwhatsapp).HandleTextMessage(0xc0005794a0, 0xc000780600, 0x20, 0xc0007805e0, 0x1a, 0x0, 0x0, 0x0, 0x5f43f4f3, 0x0, ...)
	/go/src/github.com/42wim/matterbridge/bridge/whatsapp/handlers.go:82 +0xc9
created by github.com/Rhymen/go-whatsapp.(*Conn).handleWithCustomHandlers
	/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200421062035-31e8111ac334/handler.go:202 +0x1338
```

**Comment by nathanaelhoun** [comment]
Thanks @42wim, it works flawlessly with release 1.18.2 :+1:
