### ISSUE TITLE
Mumble SIGSEGV at start

### ISSUE THREAD

**Issue by Elinvention** [42wim/matterbridge#1293]
**Describe the bug**
I was trying to setup matterbridge for a mumble server, but all I get is a SIGSEGV a few moments after I start the docker container.

**To Reproduce**
Start matterbridge with mumble configuration.

**Expected behavior**
A working mumble bot.

**Screenshots/debug logs**

```
matterbridge_1  | time="2020-11-18T22:07:11Z" level=info msg="Enabling debug logging." func=setupLogger file="matterbridge.go:106" prefix=main
matterbridge_1  | time="2020-11-18T22:07:11Z" level=info msg="Running version 1.19.0 2bb21262" func=main file="matterbridge.go:46" prefix=main
matterbridge_1  | time="2020-11-18T22:07:11Z" level=info msg="Parsing gateway gateway1" func=Start file="gateway/router.go:66" prefix=router
matterbridge_1  | time="2020-11-18T22:07:11Z" level=info msg="Starting bridge: mumble.mymumble " func=Start file="gateway/router.go:75" prefix=router
matterbridge_1  | time="2020-11-18T22:07:11Z" level=info msg="Connecting <myserver>:64738" func=Connect file="bridge/mumble/mumble.go:53" prefix=mumble
matterbridge_1  | time="2020-11-18T22:07:11Z" level=debug msg="### to markdown: **WARNING:** Your client doesn't support the Opus codec the server is using, you won't be able to talk or hear anyone. Please upgrade to a client with Opus support.
matterbridge_1  | " func=convertHTMLtoMarkdown file="bridge/mumble/helpers.go:87" prefix=mumble
matterbridge_1  | panic: runtime error: invalid memory address or nil pointer dereference
matterbridge_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x15b2bb2]
matterbridge_1  | 
matterbridge_1  | goroutine 14 [running]:
matterbridge_1  | github.com/42wim/matterbridge/bridge/mumble.(*Bmumble).handleTextMessage(0xc0000dc240, 0xc0001b8930)
matterbridge_1  | 	/go/src/github.com/42wim/matterbridge/bridge/mumble/handlers.go:31 +0x272
matterbridge_1  | layeh.com/gumble/gumbleutil.Listener.OnTextMessage(...)
matterbridge_1  | 	/go/pkg/mod/layeh.com/gumble@v0.0.0-20200818122324-146f9205029b/gumbleutil/listener.go:42
matterbridge_1  | layeh.com/gumble/gumble.(*Listeners).onTextMessage(0xc0000ce908, 0xc0001b8930)
matterbridge_1  | 	/go/pkg/mod/layeh.com/gumble@v0.0.0-20200818122324-146f9205029b/gumble/listeners.go:69 +0x9a
matterbridge_1  | layeh.com/gumble/gumble.(*Client).handleTextMessage(0xc0000d8200, 0xc000230000, 0xb6, 0xb6, 0xb6, 0x0)
matterbridge_1  | 	/go/pkg/mod/layeh.com/gumble@v0.0.0-20200818122324-146f9205029b/gumble/handlers.go:723 +0x322
matterbridge_1  | layeh.com/gumble/gumble.(*Client).readRoutine(0xc0000d8200)
matterbridge_1  | 	/go/pkg/mod/layeh.com/gumble@v0.0.0-20200818122324-146f9205029b/gumble/client.go:239 +0xbc
matterbridge_1  | created by layeh.com/gumble/gumble.DialWithDialer
matterbridge_1  | 	/go/pkg/mod/layeh.com/gumble@v0.0.0-20200818122324-146f9205029b/gumble/client.go:116 +0x269
```

**Environment (please complete the following information):**
 - OS: Manjaro
 - Matterbridge version: stable and latest docker

**Additional context**

My stripped down mattermost.toml:

```
[mumble.mymumble]
Server = "myserver:64738"
Nick = "matterbridge"
TLSClientCertificate="/etc/matterbridge/mumble.crt"
TLSClientKey="/etc/matterbridge/mumble.key"
SkipTLSVerify=false

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="mumble.mymumble"
channel="0"
```

**Comment by 42wim** [comment]
@s3lph could you take a look?
Need more nil pointers checks

**Comment by s3lph** [comment]
Unfortunately, I'm unable to reproduce this issue. Nevertheless, I think I figured out what's going on: I believe that a text message is received from the mumble server before the startup sequence (connecting to the server and joining a channel) is completed.

@Elinvention may I ask which Mumble server software your using? (Murmur vs umurmur vs grumble vs something else). I've been using matterbridge on a Murmur server without any issues, so I'm kinda confused as to why this is happening.

**Comment by Elinvention** [comment]
I use murmur and I do have a welcome text set. I tried by commenting it out, but unfortunately the error is still there.
This is `murmurd --version`: `<F>2020-12-03 22:14:26.019 murmurd -- 1.3.3`
And this is my configuration about welcometext (you can see my previous message commented out, just in case it's a unicode handling bug):

```
; Welcome message sent to clients when they connect.
; If the welcome message is set to an empty string,
; no welcome message will be sent to clients.
#welcometext="<br />Benvenuto sul nostro server <b>Mumble</b>.<br />Mumble è software libero!<br />Buon divertimento!"
welcometext=""
```

**Comment by Elinvention** [comment]
Ahah found! I was curious about this line `### to markdown: **WARNING:** Your client doesn't support the Opus codec the server is using, you won't be able to talk or hear anyone. Please upgrade to a client with Opus support.`. So, I set `opusthreshold` to 100 and this message together with the error went away. However I'd like to switch back to `opusthreshold=100`.

**Comment by s3lph** [comment]
@Elinvention can you verify that the issue is resolved in the current master branch?

> I use murmur and I do have a welcome text set.

Same setup for me.

> opusthreshold

That would explain it.

**Comment by Elinvention** [comment]
I tested with the latest docker container and apparently that commit didn't solve the issue: with opusthreshold set to 0 it still crashes.

**Comment by s3lph** [comment]
Hm with `opusthreshold=0` I can reproduce the original error, however using a version built with my patch, the message is instead discarded as intended, and no crash occurs:
```
time="2020-12-03T23:30:33+01:00" level=info msg="Starting bridge: <mybridge> " prefix=router
time="2020-12-03T23:30:33+01:00" level=info msg="Connecting <mymumble>:64738" prefix=mumble
time="2020-12-03T23:30:34+01:00" level=warning msg="Connection bootstrap not finished, discarding text message" prefix=mumble
```

@Elinvention can you make sure you're really running the latest version? Maybe you were using a cached image?

@42wim is the docker image automatically built from master?

**Comment by 42wim** [comment]
@s3lph yes `42wim/matterbridge:latest` is automatically built from master on every commit (ofcourse this could take a while on dockerhub)

**Comment by Elinvention** [comment]
I used version `version: 1.19.1-dev cbb46293`. Now I updated to `version: 1.20.1-dev 44d182e2` and I can confirm the issue is solved. Thank you all!
