### ISSUE TITLE
XMPP sends edit to Matrix, while XMPP doesn't allow edits.

### ISSUE THREAD

**Issue by mahdi1234** [42wim/matterbridge#1568]
**Describe the bug**

It happens quite often (after xmpp user did not post for some time and maybe some other condition) that new message from xmpp is sent as edit of older message, thus shown it timeline way in the past. This renders xmpp bridge quite unusable. I don't know if it's similar to https://github.com/42wim/matterbridge/issues/1396 as that seems to describe theoretical problem, but I face it often on our bridge which has only about 5 jabber users with very low activity.

**Screenshots/debug logs**

Here the original message at time="2021-08-05T07:55:27+02:00 from mkyral

is being replaced with the one

ttime="2021-08-11T06:32:36+02:00" level=debug msg="== Receiving xmpp.Chat{Remote:"openstreetmap@chat.jabb.im/mkyral"

there was no communication from that user in between (2nd log part has two messages from mkyral)

```
time="2021-08-05T07:52:50+02:00" level=debug msg=PING func=func1 file="bridge/xmpp/xmpp.go:256" prefix=xmpp
time="2021-08-05T07:54:20+02:00" level=debug msg=PING func=func1 file="bridge/xmpp/xmpp.go:256" prefix=xmpp
time="2021-08-05T07:55:08+02:00" level=debug msg="== Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@mahdi:mrdac.cz", Type:"m.room.message", Timestamp:1628142908436, ID:"$4_4zrxScoIWe6DuhOjtmHkvYy2fb586RpWNbJmFzuSA", RoomID:"!DjtOqdPZoxZMJpyRJK:matrix.org", Redacts:"", Unsigned:map[string]interface {}{"age":366}, Content:map[string]interface {}{"body":"cau", "msgtype":"m.text"}, PrevContent:map[string]interface {}(nil)}" func=handleEvent file="bridge/matrix/matrix.go:351" prefix=matrix
time="2021-08-05T07:55:09+02:00" level=debug msg="<= Sending message from @mahdi:mrdac.cz on matrix.mymatrix to gateway" func=handleEvent file="bridge/matrix/matrix.go:411" prefix=matrix
time="2021-08-05T07:55:09+02:00" level=debug msg="=> Sending config.Message{Text:"cau", Channel:"#osmcz:matrix.org", Username:"mahdi", UserID:"@mahdi:mrdac.cz", Avatar:"https://matrix.org/_matrix/media/r0/thumbnail/mrdac.cz/ropitjePnNCIFnMkSszCdbaw?width=37&height=37&method=crop", Account:"matrix.mymatrix", Event:"", Protocol:"matrix", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03afd2f5740595b, ext:643833667075613, loc:(*time.Location)(0x339b760)}, ID:"$4_4zrxScoIWe6DuhOjtmHkvYy2fb586RpWNbJmFzuSA", Extra:map[string][]interface {}(nil)} from matrix.mymatrix (#osmcz:matrix.org) to xmpp.myxmpp (openstreetmap)" func=SendMessage file="gateway/gateway.go:479" prefix=gateway
time="2021-08-05T07:55:09+02:00" level=debug msg="=> Receiving config.Message{Text:"cau", Channel:"openstreetmap", Username:"[matrix] <mahdi> ", UserID:"@mahdi:mrdac.cz", Avatar:"https://matrix.org/_matrix/media/r0/thumbnail/mrdac.cz/ropitjePnNCIFnMkSszCdbaw?width=37&height=37&method=crop", Account:"matrix.mymatrix", Event:"", Protocol:"matrix", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03afd2f5740595b, ext:643833667075613, loc:(*time.Location)(0x339b760)}, ID:"", Extra:map[string][]interface {}(nil)}" func=Send file="bridge/xmpp/xmpp.go:80" prefix=xmpp
time="2021-08-05T07:55:09+02:00" level=debug msg="=> Sending message config.Message{Text:"cau", Channel:"openstreetmap", Username:"[matrix] <mahdi> ", UserID:"@mahdi:mrdac.cz", Avatar:"https://matrix.org/_matrix/media/r0/thumbnail/mrdac.cz/ropitjePnNCIFnMkSszCdbaw?width=37&height=37&method=crop", Account:"matrix.mymatrix", Event:"", Protocol:"matrix", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03afd2f5740595b, ext:643833667075613, loc:(*time.Location)(0x339b760)}, ID:"", Extra:map[string][]interface {}(nil)}" func=Send file="bridge/xmpp/xmpp.go:134" prefix=xmpp
time="2021-08-05T07:55:09+02:00" level=debug msg="mID xmpp.myxmpp: c45nqf8ku10eqqqunvc0" func=SendMessage file="gateway/gateway.go:498" prefix=gateway
time="2021-08-05T07:55:09+02:00" level=debug msg="=> Send from matrix.mymatrix (#osmcz:matrix.org) to xmpp.myxmpp (openstreetmap) took 661.758µs" func=func1 file="gateway/gateway.go:488" prefix=gateway
time="2021-08-05T07:55:09+02:00" level=debug msg="== Receiving xmpp.Chat{Remote:"openstreetmap@chat.jabb.im/jabbim_osmcz", Type:"groupchat", Text:"[matrix] <mahdi> cau", Subject:"", Thread:"", Ooburl:"", Oobdesc:"", ID:"c45nqf8ku10eqqqunvc0", ReplaceID:"", Roster:xmpp.Roster(nil), Other:[]string{}, OtherElem:[]xmpp.XMLElement(nil), Stamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}" func=handleXMPP file="bridge/xmpp/xmpp.go:283" prefix=xmpp
time="2021-08-05T07:55:27+02:00" level=debug msg="== Receiving xmpp.Chat{Remote:"openstreetmap@chat.jabb.im/mkyral", Type:"groupchat", Text:"čau", Subject:"", Thread:"", Ooburl:"", Oobdesc:"", ID:"aadca", ReplaceID:"", Roster:xmpp.Roster(nil), Other:[]string{}, OtherElem:[]xmpp.XMLElement(nil), Stamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}" func=handleXMPP file="bridge/xmpp/xmpp.go:283" prefix=xmpp
time="2021-08-05T07:55:27+02:00" level=debug msg="<= Sending message from mkyral on xmpp.myxmpp to gateway" func=handleXMPP file="bridge/xmpp/xmpp.go:327" prefix=xmpp
time="2021-08-05T07:55:27+02:00" level=debug msg="<= Message is config.Message{Text:"čau", Channel:"openstreetmap", Username:"mkyral", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"", Gateway:"", ParentID:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"aadca", Extra:map[string][]interface {}(nil)}" func=handleXMPP file="bridge/xmpp/xmpp.go:328" prefix=xmpp
time="2021-08-05T07:55:27+02:00" level=debug msg="=> Sending config.Message{Text:"čau", Channel:"openstreetmap", Username:"mkyral", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03afd33f5601fc2, ext:643852172474508, loc:(*time.Location)(0x339b760)}, ID:"aadca", Extra:map[string][]interface {}(nil)} from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org)" func=SendMessage file="gateway/gateway.go:479" prefix=gateway
time="2021-08-05T07:55:27+02:00" level=debug msg="=> Receiving config.Message{Text:"čau", Channel:"#osmcz:matrix.org", Username:"[xmpp] <mkyral> ", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03afd33f5601fc2, ext:643852172474508, loc:(*time.Location)(0x339b760)}, ID:"", Extra:map[string][]interface {}(nil)}" func=Send file="bridge/matrix/matrix.go:129" prefix=matrix
time="2021-08-05T07:55:27+02:00" level=debug msg="Channel #osmcz:matrix.org maps to channel id !DjtOqdPZoxZMJpyRJK:matrix.org" func=Send file="bridge/matrix/matrix.go:132" prefix=matrix
time="2021-08-05T07:55:28+02:00" level=debug msg="mID matrix.mymatrix: $o0vyH28zMJBuPFsD3GYuZw4Bj4D7g3tlOEGABUVJq-g" func=SendMessage file="gateway/gateway.go:498" prefix=gateway
time="2021-08-05T07:55:28+02:00" level=debug msg="=> Send from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org) took 171.28323ms" func=func1 file="gateway/gateway.go:488" prefix=gateway
time="2021-08-05T07:55:28+02:00" level=debug msg="== Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@bot_matrix_osmcz:matrix.org", Type:"m.room.message", Timestamp:1628142927953, ID:"$o0vyH28zMJBuPFsD3GYuZw4Bj4D7g3tlOEGABUVJq-g", RoomID:"!DjtOqdPZoxZMJpyRJK:matrix.org", Redacts:"", Unsigned:map[string]interface {}{"age":133, "transaction_id":"go1628142927898280653"}, Content:map[string]interface {}{"body":"[xmpp] <mkyral> čau", "format":"org.matrix.custom.html", "formatted_body":"[xmpp] &lt;mkyral&gt; čau", "msgtype":"m.text"}, PrevContent:map[string]interface {}(nil)}" func=handleEvent file="bridge/matrix/matrix.go:351" prefix=matrix
time="2021-08-05T07:55:50+02:00" level=debug msg=PING func=func1 file="bridge/xmpp/xmpp.go:256" prefix=xmpp
time="2021-08-05T07:57:20+02:00" level=debug msg=PING func=func1 file="bridge/xmpp/xmpp.go:256" prefix=xmpp

...

time="2021-08-11T06:30:53+02:00" level=debug msg=PING func=func1 file="bridge/xmpp/xmpp.go:256" prefix=xmpp
time="2021-08-11T06:32:23+02:00" level=debug msg=PING func=func1 file="bridge/xmpp/xmpp.go:256" prefix=xmpp
time="2021-08-11T06:32:31+02:00" level=debug msg="== Receiving xmpp.Chat{Remote:"openstreetmap@chat.jabb.im/mkyral", Type:"groupchat", Text:"Ahoj, předpokládám, že v Matrixu tohle vypadá lépe ;-)", Subject:"", Thread:"", Ooburl:"", Oobdesc:"", ID:"aad7a", ReplaceID:"", Roster:xmpp.Roster(nil), Other:[]string{}, OtherElem:[]xmpp.XMLElement(nil), Stamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}" func=handleXMPP file="bridge/xmpp/xmpp.go:283" prefix=xmpp
time="2021-08-11T06:32:31+02:00" level=debug msg="<= Sending message from mkyral on xmpp.myxmpp to gateway" func=handleXMPP file="bridge/xmpp/xmpp.go:327" prefix=xmpp
time="2021-08-11T06:32:31+02:00" level=debug msg="<= Message is config.Message{Text:"Ahoj, předpokládám, že v Matrixu tohle vypadá lépe ;-)", Channel:"openstreetmap", Username:"mkyral", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"", Gateway:"", ParentID:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"aad7a", Extra:map[string][]interface {}(nil)}" func=handleXMPP file="bridge/xmpp/xmpp.go:328" prefix=xmpp
time="2021-08-11T06:32:31+02:00" level=debug msg="=> Sending config.Message{Text:"Ahoj, předpokládám, že v Matrixu tohle vypadá lépe ;-)", Channel:"openstreetmap", Username:"mkyral", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03cf297c7bd3893, ext:1157275406823717, loc:(*time.Location)(0x339b760)}, ID:"aad7a", Extra:map[string][]interface {}(nil)} from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org)" func=SendMessage file="gateway/gateway.go:479" prefix=gateway
time="2021-08-11T06:32:31+02:00" level=debug msg="=> Receiving config.Message{Text:"Ahoj, předpokládám, že v Matrixu tohle vypadá lépe ;-)", Channel:"#osmcz:matrix.org", Username:"[xmpp] <mkyral> ", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03cf297c7bd3893, ext:1157275406823717, loc:(*time.Location)(0x339b760)}, ID:"", Extra:map[string][]interface {}(nil)}" func=Send file="bridge/matrix/matrix.go:129" prefix=matrix
time="2021-08-11T06:32:31+02:00" level=debug msg="Channel #osmcz:matrix.org maps to channel id !DjtOqdPZoxZMJpyRJK:matrix.org" func=Send file="bridge/matrix/matrix.go:132" prefix=matrix
time="2021-08-11T06:32:31+02:00" level=debug msg="mID matrix.mymatrix: $TibbIjF8r9_vlV7RRzp_0Z6ZXX7UvZTKNeKPJ8gGmcA" func=SendMessage file="gateway/gateway.go:498" prefix=gateway
time="2021-08-11T06:32:31+02:00" level=debug msg="=> Send from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org) took 202.345978ms" func=func1 file="gateway/gateway.go:488" prefix=gateway
time="2021-08-11T06:32:31+02:00" level=debug msg="== Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@bot_matrix_osmcz:matrix.org", Type:"m.room.message", Timestamp:1628656351225, ID:"$TibbIjF8r9_vlV7RRzp_0Z6ZXX7UvZTKNeKPJ8gGmcA", RoomID:"!DjtOqdPZoxZMJpyRJK:matrix.org", Redacts:"", Unsigned:map[string]interface {}{"age":149, "transaction_id":"go1628656351136765029"}, Content:map[string]interface {}{"body":"[xmpp] <mkyral> Ahoj, předpokládám, že v Matrixu tohle vypadá lépe ;-)", "format":"org.matrix.custom.html", "formatted_body":"[xmpp] &lt;mkyral&gt; Ahoj, předpokládám, že v Matrixu tohle vypadá lépe ;-)", "msgtype":"m.text"}, PrevContent:map[string]interface {}(nil)}" func=handleEvent file="bridge/matrix/matrix.go:351" prefix=matrix
time="2021-08-11T06:32:36+02:00" level=debug msg="== Receiving xmpp.Chat{Remote:"openstreetmap@chat.jabb.im/mkyral", Type:"groupchat", Text:" https://upload.jabber.cz/upn2/8735ad5bc229a90a66578e2005a5ecc059230227/ueP506JeHl0q3j4PUy3UTEZrXBNuJXTGp0W6Gumk/psishare-wKYOMU.png", Subject:"", Thread:"", Ooburl:"", Oobdesc:"", ID:"aadca", ReplaceID:"", Roster:xmpp.Roster(nil), Other:[]string{"\n\n"}, OtherElem:[]xmpp.XMLElement{xmpp.XMLElement{XMLName:xml.Name{Space:"urn:xmpp:reference:0", Local:"reference"}, InnerXML:"\n<media-sharing xmlns='urn:xmpp:sims:1'>\n<file xmlns='urn:xmpp:jingle:apps:file-transfer:5'>\n<date>2021-08-11T06:33:04</date>\n<hash xmlns='urn:xmpp:hashes:2' algo='sha-1'>ALM89ddwJ/fZmhWSLmy1ZbzEmsQ=</hash>\n<media-type>image/png</media-type>\n<name>00b33cf5d77027f7d99a15922e6cb565bcc49ac4.png</name>\n<size>39759</size>\n<thumbnail xmlns='urn:xmpp:thumbs:1' height='64' mime-type='image/png' width='64' uri='cid:sha-1+2999974ee5316ff8c5fd65636e0368dde47bac85@bob.xmpp.org'/>\n</file>\n<sources>\n<reference xmlns='urn:xmpp:reference:0' type='data' uri='https://upload.jabber.cz/upn2/8735ad5bc229a90a66578e2005a5ecc059230227/ueP506JeHl0q3j4PUy3UTEZrXBNuJXTGp0W6Gumk/psishare-wKYOMU.png'/>\n<reference xmlns='urn:xmpp:reference:0' type='data' uri='xmpp:openstreetmap@chat.jabb.im/mkyral?jingle-ft'/>\n</sources>\n</media-sharing>\n"}}, Stamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}" func=handleXMPP file="bridge/xmpp/xmpp.go:283" prefix=xmpp
time="2021-08-11T06:32:36+02:00" level=debug msg="<= Sending message from mkyral on xmpp.myxmpp to gateway" func=handleXMPP file="bridge/xmpp/xmpp.go:327" prefix=xmpp
time="2021-08-11T06:32:36+02:00" level=debug msg="<= Message is config.Message{Text:" https://upload.jabber.cz/upn2/8735ad5bc229a90a66578e2005a5ecc059230227/ueP506JeHl0q3j4PUy3UTEZrXBNuJXTGp0W6Gumk/psishare-wKYOMU.png", Channel:"openstreetmap", Username:"mkyral", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"", Gateway:"", ParentID:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"aadca", Extra:map[string][]interface {}(nil)}" func=handleXMPP file="bridge/xmpp/xmpp.go:328" prefix=xmpp
time="2021-08-11T06:32:36+02:00" level=debug msg="=> Sending config.Message{Text:" https://upload.jabber.cz/upn2/8735ad5bc229a90a66578e2005a5ecc059230227/ueP506JeHl0q3j4PUy3UTEZrXBNuJXTGp0W6Gumk/psishare-wKYOMU.png", Channel:"openstreetmap", Username:"mkyral", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03cf299036dd427, ext:1157280334511815, loc:(*time.Location)(0x339b760)}, ID:"aadca", Extra:map[string][]interface {}(nil)} from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org)" func=SendMessage file="gateway/gateway.go:479" prefix=gateway
time="2021-08-11T06:32:36+02:00" level=debug msg="=> Receiving config.Message{Text:" https://upload.jabber.cz/upn2/8735ad5bc229a90a66578e2005a5ecc059230227/ueP506JeHl0q3j4PUy3UTEZrXBNuJXTGp0W6Gumk/psishare-wKYOMU.png", Channel:"#osmcz:matrix.org", Username:"[xmpp] <mkyral> ", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03cf299036dd427, ext:1157280334511815, loc:(*time.Location)(0x339b760)}, ID:"$o0vyH28zMJBuPFsD3GYuZw4Bj4D7g3tlOEGABUVJq-g", Extra:map[string][]interface {}(nil)}" func=Send file="bridge/matrix/matrix.go:129" prefix=matrix
time="2021-08-11T06:32:36+02:00" level=debug msg="Channel #osmcz:matrix.org maps to channel id !DjtOqdPZoxZMJpyRJK:matrix.org" func=Send file="bridge/matrix/matrix.go:132" prefix=matrix
time="2021-08-11T06:32:36+02:00" level=debug msg="mID matrix.mymatrix: $o0vyH28zMJBuPFsD3GYuZw4Bj4D7g3tlOEGABUVJq-g" func=SendMessage file="gateway/gateway.go:498" prefix=gateway
time="2021-08-11T06:32:36+02:00" level=debug msg="=> Send from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org) took 149.578327ms" func=func1 file="gateway/gateway.go:488" prefix=gateway
time="2021-08-11T06:32:36+02:00" level=debug msg="== Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@bot_matrix_osmcz:matrix.org", Type:"m.room.message", Timestamp:1628656356089, ID:"$jTdjDsFVPo6fORi7U89BsfrEco7gWdnmaHBIZFvgOto", RoomID:"!DjtOqdPZoxZMJpyRJK:matrix.org", Redacts:"", Unsigned:map[string]interface {}{"age":151, "transaction_id":"go1628656356059891025"}, Content:map[string]interface {}{"body":"[xmpp] <mkyral>  https://upload.jabber.cz/upn2/8735ad5bc229a90a66578e2005a5ecc059230227/ueP506JeHl0q3j4PUy3UTEZrXBNuJXTGp0W6Gumk/psishare-wKYOMU.png", "format":"org.matrix.custom.html", "formatted_body":"[xmpp] &lt;mkyral&gt; * https://upload.jabber.cz/upn2/8735ad5bc229a90a66578e2005a5ecc059230227/ueP506JeHl0q3j4PUy3UTEZrXBNuJXTGp0W6Gumk/psishare-wKYOMU.png", "m.new_content":map[string]interface {}{"body":"[xmpp] <mkyral>  https://upload.jabber.cz/upn2/8735ad5bc229a90a66578e2005a5ecc059230227/ueP506JeHl0q3j4PUy3UTEZrXBNuJXTGp0W6Gumk/psishare-wKYOMU.png", "msgtype":"m.text"}, "m.relates_to":map[string]interface {}{"event_id":"$o0vyH28zMJBuPFsD3GYuZw4Bj4D7g3tlOEGABUVJq-g", "rel_type":"m.replace"}, "msgtype":"m.text"}, PrevContent:map[string]interface {}(nil)}" func=handleEvent file="bridge/matrix/matrix.go:351" prefix=matrix
time="2021-08-11T06:33:53+02:00" level=debug msg=PING func=func1 file="bridge/xmpp/xmpp.go:256" prefix=xmpp

```

and this is matrix message after "edit"

```
Room ID: !DjtOqdPZoxZMJpyRJK:matrix.org
Event ID: $jTdjDsFVPo6fORi7U89BsfrEco7gWdnmaHBIZFvgOto
Original event source
{
  "content": {
    "body": "[xmpp] <mkyral>  https://upload.jabber.cz/upn2/8735ad5bc229a90a66578e2005a5ecc059230227/ueP506JeHl0q3j4PUy3UTEZrXBNuJXTGp0W6Gumk/psishare-wKYOMU.png",
    "format": "org.matrix.custom.html",
    "formatted_body": "[xmpp] &lt;mkyral&gt; * https://upload.jabber.cz/upn2/8735ad5bc229a90a66578e2005a5ecc059230227/ueP506JeHl0q3j4PUy3UTEZrXBNuJXTGp0W6Gumk/psishare-wKYOMU.png",
    "m.new_content": {
      "body": "[xmpp] <mkyral>  https://upload.jabber.cz/upn2/8735ad5bc229a90a66578e2005a5ecc059230227/ueP506JeHl0q3j4PUy3UTEZrXBNuJXTGp0W6Gumk/psishare-wKYOMU.png",
      "msgtype": "m.text"
    },
    "m.relates_to": {
      "event_id": "$o0vyH28zMJBuPFsD3GYuZw4Bj4D7g3tlOEGABUVJq-g",
      "rel_type": "m.replace"
    },
    "msgtype": "m.text"
  },
  "origin_server_ts": 1628656356089,
  "sender": "@bot_matrix_osmcz:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 152
  },
  "event_id": "$jTdjDsFVPo6fORi7U89BsfrEco7gWdnmaHBIZFvgOto",
  "room_id": "!DjtOqdPZoxZMJpyRJK:matrix.org"
}

```
**Environment (please complete the following information):**
 - OS: Debian stable
 - Matterbridge version: v1.22.3

**Comment by mahdi1234** [comment]
more examples from today:

todays message by one user

```
time="2021-08-17T13:23:51+02:00" level=debug msg="== Receiving xmpp.Chat{Remote:"openstreetmap@chat.jabb.im/mkyral", Type:"groupchat", Text:"Pěkné. Sice kategoricky nesouhlasím s hodnocením Geocachingu, ale budiž Mirkovi odpuštěno :-D Kolik míst já díky keškám navštívil a následně i zmapoval :-D", Subject:"", Thread:"", Ooburl:"", Oobdesc:"", ID:"aadaa", ReplaceID:"", Roster:xmpp.Roster(nil), Other:[]string{}, OtherElem:[]xmpp.XMLElement(nil), Stamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}" func=handleXMPP file="bridge/xmpp/xmpp.go:283" prefix=xmpp
time="2021-08-17T13:23:51+02:00" level=debug msg="<= Sending message from mkyral on xmpp.myxmpp to gateway" func=handleXMPP file="bridge/xmpp/xmpp.go:327" prefix=xmpp
time="2021-08-17T13:23:51+02:00" level=debug msg="<= Message is config.Message{Text:"Pěkné. Sice kategoricky nesouhlasím s hodnocením Geocachingu, ale budiž Mirkovi odpuštěno :-D Kolik míst já díky keškám navštívil a následně i zmapoval :-D", Channel:"openstreetmap", Username:"mkyral", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"", Gateway:"", ParentID:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"aadaa", Extra:map[string][]interface {}(nil)}" func=handleXMPP file="bridge/xmpp/xmpp.go:328" prefix=xmpp
time="2021-08-17T13:23:51+02:00" level=debug msg="=> Sending config.Message{Text:"Pěkné. Sice kategoricky nesouhlasím s hodnocením Geocachingu, ale budiž Mirkovi odpuštěno :-D Kolik míst já díky keškám navštívil a následně i zmapoval :-D", Channel:"openstreetmap", Username:"mkyral", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03f04f1e2a4ba7d, ext:1700355858203506, loc:(*time.Location)(0x339b760)}, ID:"aadaa", Extra:map[string][]interface {}(nil)} from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org)" func=SendMessage file="gateway/gateway.go:479" prefix=gateway
time="2021-08-17T13:23:51+02:00" level=debug msg="=> Receiving config.Message{Text:"Pěkné. Sice kategoricky nesouhlasím s hodnocením Geocachingu, ale budiž Mirkovi odpuštěno :-D Kolik míst já díky keškám navštívil a následně i zmapoval :-D", Channel:"#osmcz:matrix.org", Username:"[xmpp] <mkyral> ", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03f04f1e2a4ba7d, ext:1700355858203506, loc:(*time.Location)(0x339b760)}, ID:"$TTbrcwCiA7N4treIjQybfJzVQIzlnxv4TyUiSKr7dMM", Extra:map[string][]interface {}(nil)}" func=Send file="bridge/matrix/matrix.go:129" prefix=matrix
time="2021-08-17T13:23:51+02:00" level=debug msg="Channel #osmcz:matrix.org maps to channel id !DjtOqdPZoxZMJpyRJK:matrix.org" func=Send file="bridge/matrix/matrix.go:132" prefix=matrix
time="2021-08-17T13:23:51+02:00" level=debug msg="mID matrix.mymatrix: $TTbrcwCiA7N4treIjQybfJzVQIzlnxv4TyUiSKr7dMM" func=SendMessage file="gateway/gateway.go:498" prefix=gateway
time="2021-08-17T13:23:51+02:00" level=debug msg="=> Send from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org) took 192.048973ms" func=func1 file="gateway/gateway.go:488" prefix=gateway
time="2021-08-17T13:23:51+02:00" level=debug msg="== Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@bot_matrix_osmcz:matrix.org", Type:"m.room.message", Timestamp:1629199431670, ID:"$Ki7VIEaE7IzdlDOrJEDkYIbNK2MDCFiqodeP4iemUOE", RoomID:"!DjtOqdPZoxZMJpyRJK:matrix.org", Redacts:"", Unsigned:map[string]interface {}{"age":245, "transaction_id":"go1629199431590879308"}, Content:map[string]interface {}{"body":"[xmpp] <mkyral> Pěkné. Sice kategoricky nesouhlasím s hodnocením Geocachingu, ale budiž Mirkovi odpuštěno :-D Kolik míst já díky keškám navštívil a následně i zmapoval :-D", "format":"org.matrix.custom.html", "formatted_body":"[xmpp] &lt;mkyral&gt; * Pěkné. Sice kategoricky nesouhlasím s hodnocením Geocachingu, ale budiž Mirkovi odpuštěno :-D Kolik míst já díky keškám navštívil a následně i zmapoval :-D", "m.new_content":map[string]interface {}{"body":"[xmpp] <mkyral> Pěkné. Sice kategoricky nesouhlasím s hodnocením Geocachingu, ale budiž Mirkovi odpuštěno :-D Kolik míst já díky keškám navštívil a následně i zmapoval :-D", "msgtype":"m.text"}, "m.relates_to":map[string]interface {}{"event_id":"$TTbrcwCiA7N4treIjQybfJzVQIzlnxv4TyUiSKr7dMM", "rel_type":"m.replace"}, "msgtype":"m.text"}, PrevContent:map[string]interface {}(nil)}" func=handleEvent file="bridge/matrix/matrix.go:351" prefix=matrix
time="2021-08-17T13:24:53+02:00" level=debug msg=PING func=func1 file="bridge/xmpp/xmpp.go:256" prefix=xmpp
```

was replaced by one from totally different user on jabber side (same bot account of course)

```
time="2021-08-14T22:42:52+02:00" level=debug msg="== Receiving xmpp.Chat{Remote:"openstreetmap@chat.jabb.im/pedro'", Type:"groupchat", Text:"nebo ukonšit  track a normálně těch pár metrů dát highway=footway", Subject:"", Thread:"", Ooburl:"", Oobdesc:"", ID:"aadaa", ReplaceID:"", Roster:xmpp.Roster(nil), Other:[]string{}, OtherElem:[]xmpp.XMLElement(nil), Stamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}" func=handleXMPP file="bridge/xmpp/xmpp.go:283" prefix=xmpp
time="2021-08-14T22:42:52+02:00" level=debug msg="<= Sending message from pedro' on xmpp.myxmpp to gateway" func=handleXMPP file="bridge/xmpp/xmpp.go:327" prefix=xmpp
time="2021-08-14T22:42:52+02:00" level=debug msg="<= Message is config.Message{Text:"nebo ukonšit  track a normálně těch pár metrů dát highway=footway", Channel:"openstreetmap", Username:"pedro'", UserID:"openstreetmap@chat.jabb.im/pedro'", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"", Gateway:"", ParentID:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"aadaa", Extra:map[string][]interface {}(nil)}" func=handleXMPP file="bridge/xmpp/xmpp.go:328" prefix=xmpp
time="2021-08-14T22:42:52+02:00" level=debug msg="=> Sending config.Message{Text:"nebo ukonšit  track a normálně těch pár metrů dát highway=footway", Channel:"openstreetmap", Username:"pedro'", UserID:"openstreetmap@chat.jabb.im/pedro'", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03e28932ecc740c, ext:1474697062133393, loc:(*time.Location)(0x339b760)}, ID:"aadaa", Extra:map[string][]interface {}(nil)} from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org)" func=SendMessage file="gateway/gateway.go:479" prefix=gateway
time="2021-08-14T22:42:52+02:00" level=debug msg="=> Receiving config.Message{Text:"nebo ukonšit  track a normálně těch pár metrů dát highway=footway", Channel:"#osmcz:matrix.org", Username:"[xmpp] <pedro'> ", UserID:"openstreetmap@chat.jabb.im/pedro'", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03e28932ecc740c, ext:1474697062133393, loc:(*time.Location)(0x339b760)}, ID:"", Extra:map[string][]interface {}(nil)}" func=Send file="bridge/matrix/matrix.go:129" prefix=matrix
time="2021-08-14T22:42:52+02:00" level=debug msg="Channel #osmcz:matrix.org maps to channel id !DjtOqdPZoxZMJpyRJK:matrix.org" func=Send file="bridge/matrix/matrix.go:132" prefix=matrix
time="2021-08-14T22:42:53+02:00" level=debug msg=PING func=func1 file="bridge/xmpp/xmpp.go:256" prefix=xmpp
time="2021-08-14T22:42:53+02:00" level=debug msg="mID matrix.mymatrix: $TTbrcwCiA7N4treIjQybfJzVQIzlnxv4TyUiSKr7dMM" func=SendMessage file="gateway/gateway.go:498" prefix=gateway
time="2021-08-14T22:42:53+02:00" level=debug msg="=> Send from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org) took 1.094363293s" func=func1 file="gateway/gateway.go:488" prefix=gateway
time="2021-08-14T22:42:54+02:00" level=debug msg="== Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@bot_matrix_osmcz:matrix.org", Type:"m.room.message", Timestamp:1628973772820, ID:"$TTbrcwCiA7N4treIjQybfJzVQIzlnxv4TyUiSKr7dMM", RoomID:"!DjtOqdPZoxZMJpyRJK:matrix.org", Redacts:"", Unsigned:map[string]interface {}{"age":1203, "transaction_id":"go1628973772786173066"}, Content:map[string]interface {}{"body":"[xmpp] <pedro'> nebo ukonšit  track a normálně těch pár metrů dát highway=footway", "format":"org.matrix.custom.html", "formatted_body":"[xmpp] &lt;pedro&#39;&gt; nebo ukonšit  track a normálně těch pár metrů dát highway=footway", "msgtype":"m.text"}, PrevContent:map[string]interface {}(nil)}" func=handleEvent file="bridge/matrix/matrix.go:351" prefix=matrix
```

```
{
  "content": {
    "body": "[xmpp] <mkyral> Pěkné. Sice kategoricky nesouhlasím s hodnocením Geocachingu, ale budiž Mirkovi odpuštěno :-D Kolik míst já díky keškám navštívil a následně i zmapoval :-D",
    "format": "org.matrix.custom.html",
    "formatted_body": "[xmpp] &lt;mkyral&gt; * Pěkné. Sice kategoricky nesouhlasím s hodnocením Geocachingu, ale budiž Mirkovi odpuštěno :-D Kolik míst já díky keškám navštívil a následně i zmapoval :-D",
    "m.new_content": {
      "body": "[xmpp] <mkyral> Pěkné. Sice kategoricky nesouhlasím s hodnocením Geocachingu, ale budiž Mirkovi odpuštěno :-D Kolik míst já díky keškám navštívil a následně i zmapoval :-D",
      "msgtype": "m.text"
    },
    "m.relates_to": {
      "event_id": "$TTbrcwCiA7N4treIjQybfJzVQIzlnxv4TyUiSKr7dMM",
      "rel_type": "m.replace"
    },
    "msgtype": "m.text"
  },
  "origin_server_ts": 1629199431670,
  "sender": "@bot_matrix_osmcz:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 565823
  },
  "event_id": "$Ki7VIEaE7IzdlDOrJEDkYIbNK2MDCFiqodeP4iemUOE",
  "room_id": "!DjtOqdPZoxZMJpyRJK:matrix.org"
}
```

**Comment by mahdi1234** [comment]
and one more today's

```
time="2021-08-17T13:26:23+02:00" level=debug msg=PING func=func1 file="bridge/xmpp/xmpp.go:256" prefix=xmpp
time="2021-08-17T13:27:02+02:00" level=debug msg="== Receiving xmpp.Chat{Remote:"openstreetmap@chat.jabb.im/mkyral", Type:"groupchat", Text:"Znám. Rodinka bývá občas netrpělivá a dokonce si dovoluje odporovat :-D", Subject:"", Thread:"", Ooburl:"", Oobdesc:"", ID:"aadca", ReplaceID:"", Roster:xmpp.Roster(nil), Other:[]string{}, OtherElem:[]xmpp.XMLElement(nil), Stamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}" func=handleXMPP file="bridge/xmpp/xmpp.go:283" prefix=xmpp
time="2021-08-17T13:27:02+02:00" level=debug msg="<= Sending message from mkyral on xmpp.myxmpp to gateway" func=handleXMPP file="bridge/xmpp/xmpp.go:327" prefix=xmpp
time="2021-08-17T13:27:02+02:00" level=debug msg="<= Message is config.Message{Text:"Znám. Rodinka bývá občas netrpělivá a dokonce si dovoluje odporovat :-D", Channel:"openstreetmap", Username:"mkyral", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"", Gateway:"", ParentID:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"aadca", Extra:map[string][]interface {}(nil)}" func=handleXMPP file="bridge/xmpp/xmpp.go:328" prefix=xmpp
time="2021-08-17T13:27:02+02:00" level=debug msg="=> Sending config.Message{Text:"Znám. Rodinka bývá občas netrpělivá a dokonce si dovoluje odporovat :-D", Channel:"openstreetmap", Username:"mkyral", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03f0521a1bde098, ext:1700546843074378, loc:(*time.Location)(0x339b760)}, ID:"aadca", Extra:map[string][]interface {}(nil)} from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org)" func=SendMessage file="gateway/gateway.go:479" prefix=gateway
time="2021-08-17T13:27:02+02:00" level=debug msg="=> Receiving config.Message{Text:"Znám. Rodinka bývá občas netrpělivá a dokonce si dovoluje odporovat :-D", Channel:"#osmcz:matrix.org", Username:"[xmpp] <mkyral> ", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03f0521a1bde098, ext:1700546843074378, loc:(*time.Location)(0x339b760)}, ID:"$o0vyH28zMJBuPFsD3GYuZw4Bj4D7g3tlOEGABUVJq-g", Extra:map[string][]interface {}(nil)}" func=Send file="bridge/matrix/matrix.go:129" prefix=matrix
time="2021-08-17T13:27:02+02:00" level=debug msg="Channel #osmcz:matrix.org maps to channel id !DjtOqdPZoxZMJpyRJK:matrix.org" func=Send file="bridge/matrix/matrix.go:132" prefix=matrix
time="2021-08-17T13:27:02+02:00" level=debug msg="mID matrix.mymatrix: $o0vyH28zMJBuPFsD3GYuZw4Bj4D7g3tlOEGABUVJq-g" func=SendMessage file="gateway/gateway.go:498" prefix=gateway
time="2021-08-17T13:27:02+02:00" level=debug msg="=> Send from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org) took 136.599391ms" func=func1 file="gateway/gateway.go:488" prefix=gateway
time="2021-08-17T13:27:02+02:00" level=debug msg="== Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@bot_matrix_osmcz:matrix.org", Type:"m.room.message", Timestamp:1629199622602, ID:"$N9Ak8UzgKN3ksAvsIUhLRqUReFJ1pzrShdS5Gn9SqjM", RoomID:"!DjtOqdPZoxZMJpyRJK:matrix.org", Redacts:"", Unsigned:map[string]interface {}{"age":162, "transaction_id":"go1629199622567086606"}, Content:map[string]interface {}{"body":"[xmpp] <mkyral> Znám. Rodinka bývá občas netrpělivá a dokonce si dovoluje odporovat :-D", "format":"org.matrix.custom.html", "formatted_body":"[xmpp] &lt;mkyral&gt; * Znám. Rodinka bývá občas netrpělivá a dokonce si dovoluje odporovat :-D", "m.new_content":map[string]interface {}{"body":"[xmpp] <mkyral> Znám. Rodinka bývá občas netrpělivá a dokonce si dovoluje odporovat :-D", "msgtype":"m.text"}, "m.relates_to":map[string]interface {}{"event_id":"$o0vyH28zMJBuPFsD3GYuZw4Bj4D7g3tlOEGABUVJq-g", "rel_type":"m.replace"}, "msgtype":"m.text"}, PrevContent:map[string]interface {}(nil)}" func=handleEvent file="bridge/matrix/matrix.go:351" prefix=matrix
```

sent as edit of this one


```
time="2021-08-05T07:55:27+02:00" level=debug msg="<= Sending message from mkyral on xmpp.myxmpp to gateway" func=handleXMPP file="bridge/xmpp/xmpp.go:327" prefix=xmpp
time="2021-08-05T07:55:27+02:00" level=debug msg="<= Message is config.Message{Text:"čau", Channel:"openstreetmap", Username:"mkyral", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"", Gateway:"", ParentID:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"aadca", Extra:map[string][]interface {}(nil)}" func=handleXMPP file="bridge/xmpp/xmpp.go:328" prefix=xmpp
time="2021-08-05T07:55:27+02:00" level=debug msg="=> Sending config.Message{Text:"čau", Channel:"openstreetmap", Username:"mkyral", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03afd33f5601fc2, ext:643852172474508, loc:(*time.Location)(0x339b760)}, ID:"aadca", Extra:map[string][]interface {}(nil)} from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org)" func=SendMessage file="gateway/gateway.go:479" prefix=gateway
time="2021-08-05T07:55:27+02:00" level=debug msg="=> Receiving config.Message{Text:"čau", Channel:"#osmcz:matrix.org", Username:"[xmpp] <mkyral> ", UserID:"openstreetmap@chat.jabb.im/mkyral", Avatar:"", Account:"xmpp.myxmpp", Event:"", Protocol:"xmpp", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03afd33f5601fc2, ext:643852172474508, loc:(*time.Location)(0x339b760)}, ID:"", Extra:map[string][]interface {}(nil)}" func=Send file="bridge/matrix/matrix.go:129" prefix=matrix
time="2021-08-05T07:55:27+02:00" level=debug msg="Channel #osmcz:matrix.org maps to channel id !DjtOqdPZoxZMJpyRJK:matrix.org" func=Send file="bridge/matrix/matrix.go:132" prefix=matrix
time="2021-08-05T07:55:28+02:00" level=debug msg="mID matrix.mymatrix: $o0vyH28zMJBuPFsD3GYuZw4Bj4D7g3tlOEGABUVJq-g" func=SendMessage file="gateway/gateway.go:498" prefix=gateway
time="2021-08-05T07:55:28+02:00" level=debug msg="=> Send from xmpp.myxmpp (openstreetmap) to matrix.mymatrix (#osmcz:matrix.org) took 171.28323ms" func=func1 file="gateway/gateway.go:488" prefix=gateway
time="2021-08-05T07:55:28+02:00" level=debug msg="== Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@bot_matrix_osmcz:matrix.org", Type:"m.room.message", Timestamp:1628142927953, ID:"$o0vyH28zMJBuPFsD3GYuZw4Bj4D7g3tlOEGABUVJq-g", RoomID:"!DjtOqdPZoxZMJpyRJK:matrix.org", Redacts:"", Unsigned:map[string]interface {}{"age":133, "transaction_id":"go1628142927898280653"}, Content:map[string]interface {}{"body":"[xmpp] <mkyral> čau", "format":"org.matrix.custom.html", "formatted_body":"[xmpp] &lt;mkyral&gt; čau", "msgtype":"m.text"}, PrevContent:map[string]interface {}(nil)}" func=handleEvent file="bridge/matrix/matrix.go:351" prefix=matrix
```

```
{
  "content": {
    "body": "[xmpp] <mkyral> Znám. Rodinka bývá občas netrpělivá a dokonce si dovoluje odporovat :-D",
    "format": "org.matrix.custom.html",
    "formatted_body": "[xmpp] &lt;mkyral&gt; * Znám. Rodinka bývá občas netrpělivá a dokonce si dovoluje odporovat :-D",
    "m.new_content": {
      "body": "[xmpp] <mkyral> Znám. Rodinka bývá občas netrpělivá a dokonce si dovoluje odporovat :-D",
      "msgtype": "m.text"
    },
    "m.relates_to": {
      "event_id": "$o0vyH28zMJBuPFsD3GYuZw4Bj4D7g3tlOEGABUVJq-g",
      "rel_type": "m.replace"
    },
    "msgtype": "m.text"
  },
  "origin_server_ts": 1629199622602,
  "sender": "@bot_matrix_osmcz:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 379612
  },
  "event_id": "$N9Ak8UzgKN3ksAvsIUhLRqUReFJ1pzrShdS5Gn9SqjM",
  "room_id": "!DjtOqdPZoxZMJpyRJK:matrix.org"
}
```

**Comment by mahdi1234** [comment]
I'm downgrading to 1.18.3 for the time being as the other case suggests it wasn't problem in that version.

**Comment by 42wim** [comment]
Should be fixed in https://github.com/42wim/matterbridge/pull/1623 and latest matterbridge

**Comment by mahdi1234** [comment]
@42wim this is still happening in latest release, seen it twice today. The case you linked I believe fixed only edits to jabber side, but not from jabber.

**Comment by 42wim** [comment]
Ok, I'll reopen and take a look later when I have a jabber setup
