### ISSUE TITLE
matterbridge crash

### ISSUE THREAD

**Issue by Infernoman** [42wim/matterbridge#163]
Please answer the following questions. 

### Which version of matterbridge are you using?
version: 0.12.0-dev

### Please describe the actual behavior. 
```
time="2017-05-07T12:00:01Z" level=error msg="error:websocket: close 1006 (abnormal closure): unexpected EOF" module=matterclient
time="2017-05-07T12:00:01Z" level=info msg="Found version " module=matterclient
panic: runtime error: slice bounds out of range

goroutine 61 [running]:
github.com/42wim/matterbridge/matterclient.(*MMClient).mmVersion(0xc420194f00, 0x0)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:734 +0x6c
github.com/42wim/matterbridge/matterclient.(*MMClient).initUser(0xc420194f00, 0x0, 0x0)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:700 +0x2a2
github.com/42wim/matterbridge/matterclient.(*MMClient).Login(0xc420194f00, 0xc420049f30, 0x2)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:162 +0xc15
github.com/42wim/matterbridge/matterclient.(*MMClient).WsReceiver(0xc420194f00)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:231 +0x181
created by github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).Connect
        /root/go/src/github.com/42wim/matterbridge/bridge/mattermost/mattermost.go:74 +0x31a
2017-05-07 12:00:03,660 INFO exited: matterbridge (exit status 2; expected)
^C2017-05-08 13:03:02,024 WARN received SIGINT indicating exit request
```
#### (be sure to exclude or anonymize private data (tokens/passwords))
```
[irc]
    [irc.freenode]
    Server="irc.freenode.net:6667"
    Nick="CRW-MatterBridge"
    PrefixMessagesWithNick=true
    IgnoreNicks="travis-ci"

[mattermost]
    [mattermost.work]
        useAPI=true
        Server="SERVER"
        Team="crown"
        Login="matterbridge"
        Password="PASSWORD"
        IconURL="https://robohash.org/{NICK}.png?size=48x48"

    [mattermost.webhook]
        BindAddress="0.0.0.0:9999"
        IconURL="https://robohash.org/{NICK}.png?size=48x48"
        URL="WEBHOOK"

[slack]
    [slack.hobby]
    useAPI=true
    Token="TOKEN"
    IconURL="https://robohash.org/{NICK}.png?size=48x48"

[discord]
    [discord.game]
    Token="TOKEN"
    IconURL="https://robohash.org/{NICK}.png?size=48x48"
    Server="Crown"

[general]
RemoteNickFormat="{NICK}<{PROTOCOL}>"



# General Channels
[[gateway]]
name="mygateway"
enable=true
    [[gateway.inout]]
    account="irc.freenode"
    channel="#crowncoin"

    [[gateway.inout]]
    account="mattermost.webhook"
    channel="town-square"

    [[gateway.inout]]
    account="slack.hobby"
    channel="general"

    [[gateway.inout]]
    account="discord.game"
    channel="CHANNEL"


# Slack / Mattermost Gateways
[[samechannelgateway]]
   name="samechannelgateway"
   enable = true
   accounts = [ "mattermost.work","slack.hobby" ]
   channels = [ "altcoins","core-dev","core-dev-team","crw-tokens","developer-general","developer-marketing","github-latest","help","random","testing"]
```

**Comment by 42wim** [comment]
Thanks for reporting.
I just fixed it in master (I hope) :)

**Comment by Infernoman** [comment]
Looks like We're still having a few issues unless ive tried to update incorrectly.
```
time="2017-05-11T12:13:45Z" level=info msg="Gateway(s) started succesfully. Now relaying messages"
time="2017-05-11T18:00:01Z" level=error msg="error:websocket: close 1006 (abnormal closure): unexpected EOF" module=matterclient
time="2017-05-11T18:00:01Z" level=info msg="Found version " module=matterclient
panic: runtime error: slice bounds out of range

goroutine 61 [running]:
github.com/42wim/matterbridge/matterclient.(*MMClient).mmVersion(0xc42019d040, 0x0)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:734 +0x6c
github.com/42wim/matterbridge/matterclient.(*MMClient).initUser(0xc42019d040, 0x0, 0x0)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:700 +0x2a2
github.com/42wim/matterbridge/matterclient.(*MMClient).Login(0xc42019d040, 0xc420049f30, 0x2)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:162 +0xc15
github.com/42wim/matterbridge/matterclient.(*MMClient).WsReceiver(0xc42019d040)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:231 +0x181
created by github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).Connect
        /root/go/src/github.com/42wim/matterbridge/bridge/mattermost/mattermost.go:74 +0x31a
2017-05-11 18:00:03,794 INFO exited: matterbridge (exit status 2; expected)time="2017-05-11T12:13:45Z" level=info msg="Gateway(s) started succesfully. Now relaying messages"
time="2017-05-11T18:00:01Z" level=error msg="error:websocket: close 1006 (abnormal closure): unexpected EOF" module=matterclient
time="2017-05-11T18:00:01Z" level=info msg="Found version " module=matterclient
panic: runtime error: slice bounds out of range

goroutine 61 [running]:
github.com/42wim/matterbridge/matterclient.(*MMClient).mmVersion(0xc42019d040, 0x0)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:734 +0x6c
github.com/42wim/matterbridge/matterclient.(*MMClient).initUser(0xc42019d040, 0x0, 0x0)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:700 +0x2a2
github.com/42wim/matterbridge/matterclient.(*MMClient).Login(0xc42019d040, 0xc420049f30, 0x2)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:162 +0xc15
github.com/42wim/matterbridge/matterclient.(*MMClient).WsReceiver(0xc42019d040)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:231 +0x181
created by github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).Connect
        /root/go/src/github.com/42wim/matterbridge/bridge/mattermost/mattermost.go:74 +0x31a
2017-05-11 18:00:03,794 INFO exited: matterbridge (exit status 2; expected)
```
When i updated i cd'ed to the go folder. and followed the installation procedure again by typing go get github.com/42wim/matterbridge

**Comment by 42wim** [comment]
Try ```go get -u github.com/42wim/matterbridge``` of use latest release

**Comment by Infernoman** [comment]
That's what i was looking for :) thanks again.
