### ISSUE TITLE
Telegram is not displaying reply quotes

### ISSUE THREAD

**Issue by King-Mucus** [42wim/matterbridge#1785]
**Describe the bug**
Telegram is not displaying quoted messages from other platforms. Tested on Discord and Matrix. This didn't happen a couple releases ago.

**To Reproduce**
Just quote a message in Matrix or Discord to reply to it.

**Expected behavior**
Message being displayed according to the QuoteFormat specification, including quoted message.

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.

**Environment (please complete the following information):**
 - OS: Gentoo Linux
 - Matterbridge version: 1.24.1

**Additional context**
It also happens on the official matterbridge channels and also on supertuxkart channels, not only on mine.
![20220402_16h51m49s_grim](https://user-images.githubusercontent.com/70046572/161399419-ac070155-ea5f-48f9-a5eb-25dfdf7150b8.png)
![20220402_16h53m29s_grim](https://user-images.githubusercontent.com/70046572/161399420-f362f646-adad-4e81-bab0-7c7c1ea5e65a.png)

**Comment by King-Mucus** [comment]
It would be cool if Matterbridge could search the previous messages on the channel or group to see which one of them matches the content of QUOTEMESSAGE. This would allow Matterbridge to make a reply to such message and insert it into a typical and clickable Telegram quote block.

**Comment by 42wim** [comment]
should be fixed by https://github.com/42wim/matterbridge/pull/1776

**Comment by King-Mucus** [comment]
Hello. Just tried the new release version and this problem persists. QUOTEMESSAGE is only displayed as `[REPLY]`

log: http://dpaste.com/8MD4G4M2D

Screenshots:
![20220403_21h18m28s_grim](https://user-images.githubusercontent.com/70046572/161456201-cb080a20-22fb-4ec4-a634-78d20df59db3.png)
![20220403_21h18m48s_grim](https://user-images.githubusercontent.com/70046572/161456204-8e92b0d1-b0dd-4c19-af33-fe237e765786.png)

**Comment by 42wim** [comment]
you must set `PreserveThreading=true` in your telegram config

**Comment by King-Mucus** [comment]
Tried adding PreserveThreading=true and QuoteDisable=false, but results are the same.

Tried on another channel. Awaiting permission to send prints and logs.

My config:

`[discord]
[discord.STKL]
Token="[highly secretive token]"
Server="[server ID]"
StripNick=false
RemoteNickFormat="{NICK} (en {LABEL})"
ReplaceMessages=[ ["STK Latam bridge:",""], ["Yandex.Translate:",""] ]
IgnoreNicks="Translator"
IgnoreMessages="!tr !translate"
ShowEmbeds=true
UseUserName=false
EditSuffix=" (𝘦𝘥𝘪𝘵𝘢𝘥𝘰)"
AutoWebhooks=true
Label="Discord"

[telegram]
[telegram.STKL]
Token="[secret token]"
RemoteNickFormat="<b>{NICK}</b> <i>(en {LABEL})</i>:\n"
MessageFormat="HTMLNick"
UseFirstName=true
QuoteDisable=false
QuoteFormat="> {QUOTENICK}: \n > {QUOTEMESSAGE} \n \n {MESSAGE}"
ReplaceMessages=[ ["STK Latam bridge:",""], ["Yandex.Translate:",""] ]
IgnoreNicks="Translator"
IgnoreMessages="!tr !translate"
EditSuffix=" (𝘦𝘥𝘪𝘵𝘢𝘥𝘰)"
MediaConvertWebPToPNG=true
MediaConvertTgs="gif"
Label="Telegram"
PreserveThreading=true

[telegram.GENTOO]
Token="[secret token]"
RemoteNickFormat="<b>{NICK}</b> <i>(no {LABEL})</i>:\n"
MessageFormat="HTMLNick"
UseFirstName=true
QuoteDisable=false
QuoteFormat="<blockquote>{QUOTENICK}:<br/>{QUOTEMESSAGE}</blockquote>{MESSAGE}"
ReplaceMessages=[ ["Gentoo Brasil 🇧🇷: \n", ""], ["<blockquote>Gentoo Brasi
l 🇧🇷:<br/>", "<blockquote>"] ]
ExtractNicks=[ ["Ponte da Amisade e do Respeito", ""] ]
IgnoreNicks="Translator"
IgnoreMessages="!tr !translate"
EditSuffix=" (adulterado)"
MediaConvertWebPToPNG=true
MediaConvertTgs="gif"
Label="Telegram"
PreserveThreading=true

[matrix]
[matrix.STKL]
Server="https://matrix.org"
Login="[login]"
Password="[password]"
RemoteNickFormat="<b>{NICK}</b> <i>(en {LABEL})</i>:<br />"
NoHomeServerSuffix=true
ReplaceMessages=[ ["STK Latam bridge:",""], ["Yandex.Translate:",""] ]
IgnoreNicks="Translator"
IgnoreMessages="!tr !translate"
EditSuffix=" (𝘦𝘥𝘪𝘵𝘢𝘥𝘰)"
Label="Matrix/IRC"

[matrix.GENTOO]
Server="https://matrix.org"
Login="[ffffff]"
Password="[secret]"
RemoteNickFormat="<b>{NICK}</b> <i>(no {LABEL})</i>:<br />"
NoHomeServerSuffix=true
ExtractNicks=[ ["Ponte da Amisade e do Respeito", ""] ]
ReplaceMessages=[ ["Gentoo Brasil 🇧🇷: \n", ""], ["<blockquote>Gentoo Brasi
l 🇧🇷:<br/>", "<blockquote>"] ]
IgnoreNicks="Translator"
IgnoreMessages="!tr !translate"
EditSuffix=" (adulterado)"
Label="Matrix"

[general]
EditDisable=false
LogFile="/var/log/matterbridge.log"

[[gateway]]
name="Commons"
enable=true

[[gateway.inout]]
account="discord.STKL"
channel="[channel name]"

[[gateway.inout]]
account="telegram.STKL"
channel="[number]"

[[gateway.inout]]
account="matrix.STKL"
channel="[code]:matrix.org"

[[gateway]]
name="Admin"
enable=true

[[gateway.inout]];
account="telegram.STKL"
channel="[number"

[[gateway.inout]]
account="matrix.STKL"
channel="[code]:matrix.org"

[[gateway]]
name="GentooBR"
enable=true

[[gateway.inout]]
account="telegram.GENTOO"
channel="[number]"
#chatid="[number]"

[[gateway.inout]]
account="matrix.GENTOO"
channel="[code]:matrix.org"

[[gateway]]
name="GentooBROFF"
enable=true

[[gateway.inout]]
account="telegram.GENTOO"
channel="[number]"

[[gateway.inout]]
account="matrix.GENTOO"
channel="[code]:matrix.org"`

**Comment by King-Mucus** [comment]
Quotes started displaying correctly after a while. It is working much better than I expected.

Thank you very much for developing this.
