### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by pciavald** [42wim/matterbridge#34]
Hi, 

thank you for your work on this integration. I'm facing a segfault with this configuration : 

```
  1 [irc]
  2     [irc.canton]
  3     Server="localhost:6667"
  4     UseTLS=false
  5     Nick="canton"
  6     RemoteNickFormat="<{NICK}> "
  7 
  8 [mattermost]
  9     [mattermost.cantonHOOK]
 10     useAPI=false
 11     URL="http://localhost:8065/hooks/gnux8bnaafnt3xdmpjhyhhoopc"
 12     BindAddress="localhost:9999"
 13     PrefixMessagesWithNick=false
 14     NoTLS=true
 15     ShowJoinPart=true
 16     RemoteNickFormat="<{NICK}>"
 17 
 18     [mattermost.cantonAPI]
 19     useAPI=true
 20     Server="localhost:8065"
 21     Team="canton"
 22     Login="matterbridge"
 23     Password="*************"
 24     PrefixMessagesWithNick=false
 25     NoTLS=true
 26 
 27 [[gateway]]
 28 name="gateway1"
 29 enable=true
 30     [[gateway.in]]
 31     account="irc.canton"
 32     channel="#canton"
 33 
 34     [[gateway.in]]
 35     account="mattermost.cantonHOOK"
 36     channel="Off-Topic"
 37 
 38     [[gateway.out]]
 39     account="irc.canton"
 40     channel="#canton"
 41 
 42     [[gateway.out]]
 43     account="mattermost.cantonHOOK"
 44     channel="Off-Topic"
```

```
INFO[2016-09-19T23:11:38Z] enabling debug                               
running version 0.7.0-dev
starting gateway "gateway1"
INFO[2016-09-19T23:11:38Z] Trying IRC connection                         module=irc
2016/09/19 23:11:38 Connected to localhost:6667 (127.0.0.1:6667)
INFO[2016-09-19T23:11:38Z] Connection succeeded                          module=irc
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x60 pc=0x58a67c]

goroutine 6 [running]:
panic(0x9dce80, 0xc82000e0e0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/42wim/matterbridge/matterclient.(*MMClient).JoinChannel(0x0, 0xc8201322b0, 0x9, 0x0, 0x0)
        /home/ubuntu/documents/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:352 +0xfc
github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).JoinChannel(0xc820081480, 0xc8201322b0, 0x9, 0x0, 0x0)
        /home/ubuntu/documents/go/src/github.com/42wim/matterbridge/bridge/mattermost/mattermost.go:99 +0x45
github.com/42wim/matterbridge/gateway.New(0xc820017640, 0xc8200651d0, 0x0, 0x0)
        /home/ubuntu/documents/go/src/github.com/42wim/matterbridge/gateway/gateway.go:34 +0x45f
main.main.func1(0xc820017640, 0xc8200ffa90, 0x8, 0x1, 0xc820134240, 0x2, 0x2, 0xc8201342c0, 0x2, 0x2)
        /home/ubuntu/documents/go/src/github.com/42wim/matterbridge/matterbridge.go:39 +0x6e
created by main.main
        /home/ubuntu/documents/go/src/github.com/42wim/matterbridge/matterbridge.go:43 +0x6f5
```

Same behaviour with mattermost.toml.simple
Also, using the API works and sends from mattermost to IRC but fails silently to go from IRC to mattermost.
If I comment out the **gateway.out for mattermost**, there is no more segfault but messages aren't being forwarded to mattermost.

```
~/documents/go/bin$ go version
go version go1.6.2 linux/amd64
~/documents/go/bin$ ./matterbridge -version
version: 0.7.0-dev
/usr/local/bin/mattermost$ sudo -u mmuser ./bin/platform --version
Version: 3.4.0
Build Number: 3.4.0
Build Date: Wed Sep 14 13:04:40 UTC 2016
Build Hash: 57f25fa59c71821cc38fd220b133aa6a40815e12
Build Enterprise Ready: true
DB Version: 3.4.0
```

**Comment by ishitatsuyuki** [comment]
Also suffering from this.

**Comment by ishitatsuyuki** [comment]
This is a improper handling for the login error. In my case, it was the email not verified for the bot user. Anyway, this should be fixed for handling properly.

**Comment by 42wim** [comment]
@pciavald Hi, thanks for the report. Could you tell me on what commit you build this ?
```git rev-parse HEAD```

**Comment by pciavald** [comment]
Great, there's no more segfault. Thank you ! I'm still not getting the messages from irc into Mattermost though. Continuing in #31
