### ISSUE TITLE
Mattermost → Slack avatars not synced

### ISSUE THREAD

**Issue by ArchangeGabriel** [42wim/matterbridge#454]
**Describe the bug**
I’m using a WebHook + Bot setup in both services, messages are sent fine but avatars are not displayed.

**To Reproduce**
Configure a WebHook + Bot setup in a Slack and a Mattermost together, using a `samechannelgateway`.

**Expected behavior**
Avatar of Mattermost users should be displayed with their messages in Slack.

**Screenshots/debug logs**
In the debug log, I see `Avatar:""` for those messages.

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: 1.11.0
 - If self compiled: used the tag.

**Comment by ArchangeGabriel** [comment]
Also, when Slack user have no avatar set, there is no picture at all but “user profile image” written one word per line.

**Comment by 42wim** [comment]
To have mattermost avatar working you need to use the mediaserver setup. (https://github.com/42wim/matterbridge/wiki/Mediaserver-setup-%5Badvanced%5D)

This is because mattermost avatar images aren't public by default and will need to be downloaded and uploaded to the mediaserver, to be served at slack.

So this works as designed, I'll add this information to the FAQ because it isn't that clear

**Comment by ArchangeGabriel** [comment]
Indeed that wasn’t clear, and I also thought that since the doc says Slack and Mattermost support having documents being uploaded on each side, this would include avatars. But I understand why that is not the case, because strictly speaking those are not documents upload events.

I will try with mediaserver then.

**Comment by ArchangeGabriel** [comment]
Especially the confusing part:
```
This mediaserver will be used to upload media to services that don't have support for uploading images/video/files.
```

BTW, do you know if anyone configured it with nginx and the upload plugin?

**Comment by 42wim** [comment]
No sorry, no idea about nginx, but should work.

Would very much appreciate it if you got it working with nginx you could add an howto beneath caddy on https://github.com/42wim/matterbridge/wiki/Mediaserver-setup-%5Badvanced%5D

**Comment by ArchangeGabriel** [comment]
Apparently Nginx upload plugin is a bit old and currently not compatible. However since MediaServerUpload and Download are two different settings, I might work around this by having a Caddy server listening on localhost for files to be uploaded and serve them through nginx afterwards. That should work, right?

**Comment by ArchangeGabriel** [comment]
That’s even better, thanks for this (I guess that if I had actually started looking at implementing my idea I would have seen this option, but now I know that it will be easy :D).

**Comment by ArchangeGabriel** [comment]
Slack → Mattermost working case (a.k.a. me and that’s all):
```
[0673] DEBUG slack:        == Receiving event &slack.MessageEvent{Msg:slack.Msg{Type:"message", Channel:"<redacted>", User:"<redacted>", Text:"<redacted>", Timestamp:"<redacted>", ThreadTimestamp:"", IsStarred:false, PinnedTo:[]string(nil), Attachments:[]slack.Attachment(nil), Edited:(*slack.Edited)(nil), SubType:"", Hidden:false, DeletedTimestamp:"", EventTimestamp:"<redacted>", BotID:"", Username:"", Icons:(*slack.Icon)(nil), Inviter:"", Topic:"", Purpose:"", Name:"", OldName:"", Members:[]string(nil), ReplyCount:0, Replies:[]slack.Reply(nil), ParentUserId:"", File:(*slack.File)(nil), Upload:false, Comment:(*slack.Comment)(nil), ItemType:"", ReplyTo:0, Team:"<redacted>", Reactions:[]slack.ItemReaction(nil)}, SubMessage:(*slack.Msg)(nil)}
[0673] DEBUG slack:        <= Sending message from <redacted> on slack.<redacted> to gateway
[0673] DEBUG slack:        <= Message is &config.Message{Text:"<redacted>", Channel:"town-square", Username:"<redacted>", UserID:"<redacted>", Avatar:"https://avatars.slack-edge.com/<redacted>.jpg", Account:"slack.<redacted>", Event:"", Protocol:"", Gateway:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"slack <redacted>", Extra:map[string][]interface {}{}}
[0673] DEBUG gateway:      => Sending config.Message{Text:"<redacted>", Channel:"town-square", Username:"<redacted>", UserID:"<redacted>", Avatar:"https://avatars.slack-edge.com/<redacted>.jpg", Account:"slack.<redacted>", Event:"", Protocol:"", Gateway:"gateway_<redacted>", Timestamp:time.Time{wall:0x<redacted>, ext:<redacted>, loc:(*time.Location)(0x<redacted>)}, ID:"slack <redacted>", Extra:map[string][]interface {}{}} from slack.<redacted> (town-square) to mattermost.<redacted> (town-square)
[0673] DEBUG mattermost:   => Receiving config.Message{Text:"<redacted>", Channel:"town-square", Username:"<redacted>", UserID:"<redacted>", Avatar:"https://avatars.slack-edge.com/<redacted>.jpg", Account:"slack.<redacted>", Event:"", Protocol:"", Gateway:"gateway_<redacted>", Timestamp:time.Time{wall:0x<redacted>, ext:<redacted>, loc:(*time.Location)(0x<redacted>)}, ID:"", Extra:map[string][]interface {}{}}
[0674] DEBUG matterclient: WsReceiver event: model.WebSocketEvent{Event:"posted", Data:map[string]interface {}{"team_id":"<redacted>", "channel_display_name":"<redacted>", "channel_name":"town-square", "channel_type":"O", "post":"{\"id\":\"<redacted>\",\"create_at\":<redacted>,\"update_at\":<redacted>,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"<redacted>\",\"channel_id\":\"<redacted>\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"<redacted>\",\"type\":\"\",\"props\":{\"from_webhook\":\"true\",\"matterbridge_<redacted>\":true,\"override_icon_url\":\"https://avatars.slack-edge.com/<redacted>.jpg\",\"override_username\":\"<redacted>\",\"webhook_display_name\":\"Matterbridge <redacted>\"},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"<redacted>"}, Broadcast:(*model.WebsocketBroadcast)(0xc<redacted>), Sequence:5}
[0674] DEBUG mattermost:   map[string]interface {}{"team_id":"<redacted>", "channel_display_name":"<redacted>", "channel_name":"town-square", "channel_type":"O", "post":"{\"id\":\"<redacted>\",\"create_at\":<redacted>,\"update_at\":<redacted>,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"<redacted>\",\"channel_id\":\"<redacted>\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"<redacted>\",\"type\":\"\",\"props\":{\"from_webhook\":\"true\",\"matterbridge_<redacted>\":true,\"override_icon_url\":\"https://avatars.slack-edge.com/<redacted>.jpg\",\"override_username\":\"<redacted>\",\"webhook_display_name\":\"Matterbridge <redacted>\"},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"<redacted>"}
[0674] DEBUG mattermost:   sent by matterbridge, ignoring
[0674] DEBUG mattermost:   Skipped message: &matterclient.Message{Raw:(*model.WebSocketEvent)(0x<redacted>), Post:(*model.Post)(0x<redacted>), Team:"<redacted>", Channel:"town-square", Username:"<redacted>", Text:"<redacted>", Type:"", UserID:"<redacted>"}
```

**Comment by ArchangeGabriel** [comment]
Not working case:
```
[1620] DEBUG slack:        == Receiving event &slack.MessageEvent{Msg:slack.Msg{Type:"message", Channel:"<redacted>", User:"<redacted>", Text:"Flood", Timestamp:"<redacted>", ThreadTimestamp:"", IsStarred:false, PinnedTo:[]string(nil), Attachments:[]slack.Attachment(nil), Edited:(*slack.Edited)(nil), SubType:"", Hidden:false, DeletedTimestamp:"", EventTimestamp:"<redacted>", BotID:"", Username:"", Icons:(*slack.Icon)(nil), Inviter:"", Topic:"", Purpose:"", Name:"", OldName:"", Members:[]string(nil), ReplyCount:0, Replies:[]slack.Reply(nil), ParentUserId:"", File:(*slack.File)(nil), Upload:false, Comment:(*slack.Comment)(nil), ItemType:"", ReplyTo:0, Team:"<redacted>", Reactions:[]slack.ItemReaction(nil)}, SubMessage:(*slack.Msg)(nil)}
[1620] DEBUG slack:        <= Sending message from <redacted> on slack.<redacted> to gateway
[1620] DEBUG slack:        <= Message is &config.Message{Text:"Flood", Channel:"town-square", Username:"<redacted>", UserID:"<redacted>", Avatar:"", Account:"slack.<redacted>", Event:"", Protocol:"", Gateway:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"slack <redacted>", Extra:map[string][]interface {}{}}
[1620] DEBUG gateway:      => Sending config.Message{Text:"Flood", Channel:"town-square", Username:"<redacted>", UserID:"<redacted>", Avatar:"", Account:"slack.<redacted>", Event:"", Protocol:"", Gateway:"gateway_<redacted>", Timestamp:time.Time{wall:0x<redacted>, ext:<redacted>, loc:(*time.Location)(0x<redacted>)}, ID:"slack <redacted>", Extra:map[string][]interface {}{}} from slack.<redacted> (town-square) to mattermost.<redacted> (town-square)
[1620] DEBUG mattermost:   => Receiving config.Message{Text:"Flood", Channel:"town-square", Username:"<redacted>", UserID:"<redacted>", Avatar:"", Account:"slack.<redacted>", Event:"", Protocol:"", Gateway:"gateway_<redacted>", Timestamp:time.Time{wall:0x<redacted>, ext:<redacted>, loc:(*time.Location)(0x<redacted>)}, ID:"", Extra:map[string][]interface {}{}}
[1621] DEBUG matterclient: WS PING
[1621] DEBUG matterclient: sendWsRequest &model.WebSocketRequest{Seq:28, Action:"ping", Data:map[string]interface {}(nil), Session:model.Session{Id:"", Token:"", CreateAt:0, ExpiresAt:0, LastActivityAt:0, UserId:"", DeviceId:"", Roles:"", IsOAuth:false, Props:model.StringMap(nil), TeamMembers:[]*model.TeamMember(nil)}, T:(i18n.TranslateFunc)(nil), Locale:""}
[1621] DEBUG matterclient: WsReceiver response: model.WebSocketResponse{Status:"OK", SeqReply:28, Data:map[string]interface {}{"node_id":"", "server_time":<redacted>, "text":"pong", "version":"5.0.0"}, Error:(*model.AppError)(nil)}
[1621] DEBUG matterclient: WS PONG received
[1621] DEBUG matterclient: WsReceiver event: model.WebSocketEvent{Event:"posted", Data:map[string]interface {}{"team_id":"<redacted>", "channel_display_name":"<redacted>", "channel_name":"town-square", "channel_type":"O", "post":"{\"id\":\"<redacted>\",\"create_at\":<redacted>,\"update_at\":<redacted>,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"<redacted>\",\"channel_id\":\"<redacted>\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"Flood\",\"type\":\"\",\"props\":{\"from_webhook\":\"true\",\"matterbridge_<redacted>\":true,\"override_username\":\"<redacted>\",\"webhook_display_name\":\"Matterbridge <redacted>\"},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"<redacted>"}, Broadcast:(*model.WebsocketBroadcast)(0x<redacted>), Sequence:11}
[1621] DEBUG mattermost:   map[string]interface {}{"channel_display_name":"<redacted>", "channel_name":"town-square", "channel_type":"O", "post":"{\"id\":\"<redacted>\",\"create_at\":<redacted>,\"update_at\":<redacted>,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"<redacted>\",\"channel_id\":\"<redacted>\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"Flood\",\"type\":\"\",\"props\":{\"from_webhook\":\"true\",\"matterbridge_<redacted>\":true,\"override_username\":\"<redacted>\",\"webhook_display_name\":\"Matterbridge <redacted>\"},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"<redacted>", "team_id":"<redacted>"}
[1621] DEBUG mattermost:   sent by matterbridge, ignoring
[1621] DEBUG mattermost:   Skipped message: &matterclient.Message{Raw:(*model.WebSocketEvent)(0x<redacted>), Post:(*model.Post)(0x<redacted>), Team:"<redacted>", Channel:"town-square", Username:"<redacted>", Text:"Flood", Type:"", UserID:"<redacted>"}
```

**Comment by ArchangeGabriel** [comment]
BTW, those lines:
```DEBUG mattermost:   Skipped message: &matterclient.Message{Raw:(*model.WebSocketEvent)(0x<redacted>), Post:(*model.Post)(0x<redacted>), Team:"<redacted>", Channel:"town-square", Username:"<redacted>", Text:"Flood", Type:"", UserID:"<redacted>"}```
always have me as `Username`. Is that expected?

**Comment by ArchangeGabriel** [comment]
Default avatar working case:
```
[0845] DEBUG slack:        == Receiving event &slack.MessageEvent{Msg:slack.Msg{Type:"message", Channel:"<redacted>", User:"<redacted>", Text:"<redacted>", Timestamp:"<redacted>", ThreadTimestamp:"", IsStarred:false, PinnedTo:[]string(nil), Attachments:[]slack.Attachment(nil), Edited:(*slack.Edited)(nil), SubType:"", Hidden:false, DeletedTimestamp:"", EventTimestamp:"<redacted>", BotID:"", Username:"", Icons:(*slack.Icon)(nil), Inviter:"", Topic:"", Purpose:"", Name:"", OldName:"", Members:[]string(nil), ReplyCount:0, Replies:[]slack.Reply(nil), ParentUserId:"", File:(*slack.File)(nil), Upload:false, Comment:(*slack.Comment)(nil), ItemType:"", ReplyTo:0, Team:"<redacted>", Reactions:[]slack.ItemReaction(nil)}, SubMessage:(*slack.Msg)(nil)}
[0846] DEBUG slack:        <= Sending message from <redacted> on slack.<redacted> to gateway
[0846] DEBUG slack:        <= Message is &config.Message{Text:"<redacted>", Channel:"town-square", Username:"<redacted>", UserID:"<redacted>", Avatar:"https://secure.gravatar.com/avatar/fc68beb41ff6279203be3c6dd18d1447.jpg?s=48&d=https%3A%2F%2Fcfr.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0007-48.png", Account:"slack.<redacted>", Event:"", Protocol:"", Gateway:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"slack <redacted>", Extra:map[string][]interface {}{}}
[0846] DEBUG gateway:      => Sending config.Message{Text:"<redacted>", Channel:"town-square", Username:"<redacted>", UserID:"<redacted>", Avatar:"https://secure.gravatar.com/avatar/fc68beb41ff6279203be3c6dd18d1447.jpg?s=48&d=https%3A%2F%2Fcfr.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0007-48.png", Account:"slack.<redacted>", Event:"", Protocol:"", Gateway:"gateway_<redacted>", Timestamp:time.Time{wall:0x<redacted>, ext:<redacted>, loc:(*time.Location)(0x2f4f9a7c800)}, ID:"slack <redacted>", Extra:map[string][]interface {}{}} from slack.<redacted> (town-square) to mattermost.<redacted> (town-square)
[0846] DEBUG mattermost:   => Receiving config.Message{Text:"<redacted>", Channel:"town-square", Username:"<redacted>", UserID:"<redacted>", Avatar:"https://secure.gravatar.com/avatar/fc68beb41ff6279203be3c6dd18d1447.jpg?s=48&d=https%3A%2F%2Fcfr.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0007-48.png", Account:"slack.<redacted>", Event:"", Protocol:"", Gateway:"gateway_<redacted>", Timestamp:time.Time{wall:0x<redacted>, ext:<redacted>, loc:(*time.Location)(0x<redacted>)}, ID:"", Extra:map[string][]interface {}{}}
[0846] DEBUG matterclient: WsReceiver event: model.WebSocketEvent{Event:"posted", Data:map[string]interface {}{"channel_display_name":"General Discussions", "channel_name":"town-square", "channel_type":"O", "post":"{\"id\":\"<redacted>\",\"create_at\":<redacted>,\"update_at\":<redacted>,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"<redacted>\",\"channel_id\":\"<redacted>\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"<redacted>\",\"type\":\"\",\"props\":{\"from_webhook\":\"true\",\"matterbridge_<redacted>\":true,\"override_icon_url\":\"https://secure.gravatar.com/avatar/fc68beb41ff6279203be3c6dd18d1447.jpg?s=48\\u0026d=https%3A%2F%2Fcfr.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0007-48.png\",\"override_username\":\"<redacted>\",\"webhook_display_name\":\"Matterbridge <redacted>\"},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"<redacted>", "team_id":"<redacted>"}, Broadcast:(*model.WebsocketBroadcast)(0x<redacted>), Sequence:6}
[0846] DEBUG mattermost:   map[string]interface {}{"channel_name":"town-square", "channel_type":"O", "post":"{\"id\":\"<redacted>\",\"create_at\":<redacted>,\"update_at\":<redacted>,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"<redacted>\",\"channel_id\":\"<redacted>\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"<redacted>\",\"type\":\"\",\"props\":{\"from_webhook\":\"true\",\"matterbridge_<redacted>\":true,\"override_icon_url\":\"https://secure.gravatar.com/avatar/fc68beb41ff6279203be3c6dd18d1447.jpg?s=48\\u0026d=https%3A%2F%2Fcfr.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0007-48.png\",\"override_username\":\"<redacted>\",\"webhook_display_name\":\"Matterbridge <redacted>\"},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"<redacted>", "team_id":"<redacted>", "channel_display_name":"<redacted>"}
[0846] DEBUG mattermost:   sent by matterbridge, ignoring
[0846] DEBUG mattermost:   Skipped message: &matterclient.Message{Raw:(*model.WebSocketEvent)(0x<redacted>), Post:(*model.Post)(0x<redacted>), Team:"<redacted>", Channel:"town-square", Username:"<redacted>", Text:"<redacted>", Type:"", UserID:"<redacted>"}
```

**Comment by 42wim** [comment]
Could you please paste your complete config ? be sure to obfuscate tokens

**Comment by ArchangeGabriel** [comment]
```
[mattermost]
[mattermost.<redacted>]
Server="<redacted>:443"
Team="<redacted>"
Token="<redacted>"
NoTLS=false
WebhookURL="<redacted>"
ShowJoinPart=true

[slack]
[slack.<redacted>]
Token="<redacted>"
WebhookURL="<redacted>"
ShowJoinPart=true

[general]
RemoteNickFormat="{NICK} [{PROTOCOL}]"
MediaDownloadPath="<redacted>"
MediaServerDownload="<redacted>"

[[samechannelgateway]]
   name="<redacted>"
   enable = true
   accounts = [ "mattermost.<redacted>", "slack.<redacted>" ]
   channels = [ "town-square", "<redacted>" ]
```

I went quite hard on redaction, if you need one of the redacted value please tell me.

**Comment by 42wim** [comment]
Ok, was a bug with `MediaDownloadPath` not being used for avatar downloads.
This has been fixed in master, you can try dev binaries from https://bintray.com/42wim/nightly/Matterbridge/v1.11.0-9-gfa0c402#files

**Comment by 42wim** [comment]
Also, the first time you say something the avatar will be downloaded, so it's not visible on the slack side yet.
The next time the same person says something it will be visible

**Comment by ArchangeGabriel** [comment]
Hum… So I’ve patched my build with fa0c402, and now avatars from Mattermost are properly added to my MediaDownloadPath, but they still don’t show on Slack even after sending several messages.

I still have `Avatar:""` in the log when manually running the bridge.

And in the Slack → Mattermost direction, only my avatar + default avatars are shown, other custom ones are not…

**Comment by 42wim** [comment]
They should show up, could you paste a debug log again ?

If you keep retrying with the same user from mattermost -> slack it won't show the avatar, because the webhook image will only change when a new person says something.

So to actually test it from mattermost -> slack

person1 on mattermost say something
person2 on mattermost say something
person1 on mattermost say something <= now the person1 avatar will start showing
person2 on mattermost say something <= now the person2 avatar will start showing

For slack -> mattermost issues, please open a new ticket

**Comment by ArchangeGabriel** [comment]
Hum… That could have explained, because I was the only one on the mattermost side speaking during those tests.

But since then someone else spoke, and then I did again. And my avatar is still not showing. Here is a new log:
```
[0007] DEBUG matterclient: WsReceiver event: model.WebSocketEvent{Event:"typing", Data:map[string]interface {}{"parent_id":"", "user_id":"<mymattermostuuid>"}, Broadcast:(*model.WebsocketBroadcast)(0x<redacted>), Sequence:2}
[0012] DEBUG matterclient: WsReceiver event: model.WebSocketEvent{Event:"typing", Data:map[string]interface {}{"user_id":"mymattermostuuid>", "parent_id":""}, Broadcast:(*model.WebsocketBroadcast)(0x<redacted>), Sequence:3}
[0015] DEBUG matterclient: WsReceiver event: model.WebSocketEvent{Event:"posted", Data:map[string]interface {}{"team_id":"<teamid>", "channel_display_name":"General Discussions", "channel_name":"town-square", "channel_type":"O", "post":"{\"id\":\"<randomid>\",\"create_at\":<timestamp>,\"update_at\":<timestamp>,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"<mymattermostuuid>\",\"channel_id\":\"<randomid>\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"<mymessage>\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"<mymattermostuuid>:<timestamp>\"}", "sender_name":"<myuserlogin>"}, Broadcast:(*model.WebsocketBroadcast)(0x<redacted>), Sequence:4}
[0015] DEBUG mattermost:   map[string]interface {}{"channel_display_name":"General Discussions", "channel_name":"town-square", "channel_type":"O", "post":"{\"id\":\"<randomid>\",\"create_at\":<timestamp>,\"update_at\":<timestamp>,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"<mymattermostuuid>\",\"channel_id\":\"<randomid>\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"<mymessage>\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"<mymattermostuuid>:<timestamp>\"}", "sender_name":"<myuserlogin>", "team_id":"<teamid>"}
[0015] DEBUG mattermost:   Trying to download "<mymattermostuuid>.png" with size 27338
[0015] DEBUG mattermost:   Download OK "<mymattermostuuid>.png" 27338
[0015] DEBUG mattermost:   == Receiving event &matterclient.Message{Raw:(*model.WebSocketEvent)(0x<redacted>), Post:(*model.Post)(0x<redacted>), Team:"<teamname>", Channel:"town-square", Username:"<myuserlogin>", Text:"<mymessage>", Type:"", UserID:"<mymattermostuuid>"}
[0015] DEBUG mattermost:   <= Sending message from <myuserlogin> on mattermost.<teamname> to gateway
[0015] DEBUG mattermost:   <= Message is &config.Message{Text:"<mymessage>", Channel:"town-square", Username:"<myuserlogin>", UserID:"<mymattermostuuid>", Avatar:"", Account:"mattermost.<teamname>", Event:"", Protocol:"", Gateway:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"<randomid>", Extra:map[string][]interface {}{}}
[0015] DEBUG gateway:      mediaserver path placing file: <MediaPath>//<shortid>/<mymattermostuuid>.png
[0015] ERROR gateway:      mediaserver path failed, could not writefile: open <MediaPath>//<shortid>/<mymattermostuuid>.png: permission denied &os.PathError{Op:"open", Path:"<MediaPath>//<shortid>/<mymattermostuuid>.png", Err:0xd}
[0015] DEBUG gateway:      => Sending config.Message{Text:"<mymessage>", Channel:"town-square", Username:"<myuserlogin>", UserID:"<mymattermostuuid>", Avatar:"", Account:"mattermost.<teamname>", Event:"", Protocol:"", Gateway:"gateway_<teamname>", Timestamp:time.Time{wall:0x<randomid>, ext:<timestamp>, loc:(*time.Location)(0x<redacted>)}, ID:"<randomid>", Extra:map[string][]interface {}{}} from mattermost.<teamname> (town-square) to slack.<teamname> (town-square)
[0015] DEBUG slack:        => Receiving config.Message{Text:"<mymessage>", Channel:"town-square", Username:"<myuserlogin> [mattermost]", UserID:"<mymattermostuuid>", Avatar:"", Account:"mattermost.<teamname>", Event:"", Protocol:"", Gateway:"gateway_<teamname>", Timestamp:time.Time{wall:0x<randomid>, ext:<timestamp>, loc:(*time.Location)(0x<redacted>)}, ID:"", Extra:map[string][]interface {}{}}
[0015] DEBUG slack:        == Receiving event &slack.MessageEvent{Msg:slack.Msg{Type:"message", Channel:"<chanid>", User:"", Text:"<mymessage>", Timestamp:"<timestamp>", ThreadTimestamp:"", IsStarred:false, PinnedTo:[]string(nil), Attachments:[]slack.Attachment(nil), Edited:(*slack.Edited)(nil), SubType:"bot_message", Hidden:false, DeletedTimestamp:"", EventTimestamp:"<timestamp>", BotID:"BBCDZPFDY", Username:"<myuserlogin> [mattermost]", Icons:(*slack.Icon)(nil), Inviter:"", Topic:"", Purpose:"", Name:"", OldName:"", Members:[]string(nil), ReplyCount:0, Replies:[]slack.Reply(nil), ParentUserId:"", File:(*slack.File)(nil), Upload:false, Comment:(*slack.Comment)(nil), ItemType:"", ReplyTo:0, Team:"<teamid>", Reactions:[]slack.ItemReaction(nil)}, SubMessage:(*slack.Msg)(nil)}
[0015] ERROR slack:        &errors.errorString{s:"probably an incoming webhook we couldn't resolve (maybe ourselves)"}
```

**Comment by 42wim** [comment]
Well, it clearly shows the error
```[0015] ERROR gateway:      mediaserver path failed, could not writefile: open <MediaPath>//<shortid>/<mymattermostuuid>.png: permission denied &os.PathError{Op:"open", Path:"<MediaPath>//<shortid>/<mymattermostuuid>.png", Err:0xd}```

matterbridge hasn't got the right permission to save the files

**Comment by ArchangeGabriel** [comment]
But it did write it, because the file exists.

**Comment by ArchangeGabriel** [comment]
If I can join you somewhere on IRC or Matrix to debug this, I’m available currently.

**Comment by ArchangeGabriel** [comment]
Token log start (I’ve just removed the other joined channels):
```
[0000]  INFO main:         Enabling debug
[0000]  INFO main:         Running version 1.11.0 
ERROR 2018/07/14 21:57:43 Couldn't discover absolute path
ERROR 2018/07/14 21:57:43 stat .: permission denied
[0000]  INFO gateway:      Parsing gateway gateway_<team>
[0000]  INFO gateway:      Starting bridge: mattermost.<team> 
[0000]  INFO mattermost:   Connecting using webhookurl (sending)
[0000]  INFO mattermost:   Connecting using token (receiving)
[0000]  INFO mattermost:   Connecting  (team: <team>) on <mattermosturl>:443
[0000]  INFO matterclient: Found version 5.0.0.5.0.0-1.963e1365d555e55477abe435a3ed828e.false
[0000] DEBUG matterclient: trying login <team>  <mattermosturl>:443
[0000] DEBUG matterclient: trying login with token
[0000] DEBUG matterclient: initUser(): found our team <team> (id: <teamid>)
[0000] DEBUG matterclient: WsClient: making connection: wss://<mattermosturl>:443/api/v4/websocket
[0000] DEBUG matterclient: WsClient: connected
[0000]  INFO mattermost:   Connection succeeded
[0000]  INFO bridge:       mattermost.<team>: joining test (ID: testmattermost.<team>)
[0000]  INFO bridge:       mattermost.<team>: joining town-square (ID: town-squaremattermost.<team>)
[0000] DEBUG matterclient: StatusLoop:<nil>
[0000] DEBUG matterclient: WS PING
[0000]  INFO gateway:      Starting bridge: slack.<team> 
[0000] DEBUG matterclient: WsReceiver event: model.WebSocketEvent{Event:"hello", Data:map[string]interface {}{"server_version":"5.0.0.5.0.0-1.963e1365d555e55477abe435a3ed828e.false"}, Broadcast:(*model.WebsocketBroadcast)(0xc4204dc400), Sequence:0}
[0000] DEBUG matterclient: sendWsRequest &model.WebSocketRequest{Seq:1, Action:"ping", Data:map[string]interface {}(nil), Session:model.Session{Id:"", Token:"", CreateAt:0, ExpiresAt:0, LastActivityAt:0, UserId:"", DeviceId:"", Roles:"", IsOAuth:false, Props:model.StringMap(nil), TeamMembers:[]*model.TeamMember(nil)}, T:(i18n.TranslateFunc)(nil), Locale:""}
[0000] DEBUG mattermost:   Choosing token based receiving
[0000]  INFO slack:        Connecting using webhookurl (sending)
[0000]  INFO slack:        Connecting using token (receiving)
[0000]  INFO bridge:       slack.<team>: joining town-square (ID: town-squareslack.<team>)
[0000] DEBUG matterclient: WsReceiver response: model.WebSocketResponse{Status:"OK", SeqReply:1, Data:map[string]interface {}{"node_id":"", "server_time":1.5<redacted>e+12, "text":"pong", "version":"5.0.0"}, Error:(*model.AppError)(nil)}
[0000] DEBUG matterclient: WS PONG received
[0000] DEBUG slack:        Choosing token based receiving
[0000] DEBUG slack:        == Receiving event &slack.ConnectingEvent{Attempt:1, ConnectionCount:1}
[0000] DEBUG matterclient: WsReceiver event: model.WebSocketEvent{Event:"status_change", Data:map[string]interface {}{"status":"online", "user_id":"<someid>"}, Broadcast:(*model.WebsocketBroadcast)(0xc420516100), Sequence:1}
[0000] DEBUG slack:        == Receiving event &slack.ConnectedEvent{ConnectionCount:1, Info:(*slack.Info)(0xc4206b0000)}
[0001]  INFO bridge:       slack.<team>: joining test (ID: testslack.<team>)
[0001] DEBUG slack:        == Receiving event &slack.HelloEvent{}
[0001]  INFO main:         Gateway(s) started succesfully. Now relaying messages
[0001] DEBUG slack:        Start listening for Slack messages
```

**Comment by ArchangeGabriel** [comment]
User/pass one:
```
[0000]  INFO main:         Enabling debug
[0000]  INFO main:         Running version 1.11.0 
ERROR 2018/07/14 22:09:40 Couldn't discover absolute path
ERROR 2018/07/14 22:09:40 stat .: permission denied
[0000]  INFO gateway:      Parsing gateway gateway_<team>
[0000]  INFO gateway:      Starting bridge: mattermost.<team> 
[0000]  INFO mattermost:   Connecting using webhookurl (sending)
[0000]  INFO mattermost:   Connecting using login/password (receiving)
[0000]  INFO mattermost:   Connecting <botuser> (team: <team>) on <mattermosturl>:443
[0000]  INFO matterclient: Found version 5.0.0.5.0.0-1.963e1365d555e55477abe435a3ed828e.false
[0000] DEBUG matterclient: trying login <team> <botuser> <mattermosturl>:443
[0000] DEBUG matterclient: initUser(): found our team <team> (id: <teamid>)
[0000] DEBUG matterclient: WsClient: making connection: wss://<mattermosturl>:443/api/v4/websocket
[0000] DEBUG matterclient: WsClient: connected
[0000]  INFO mattermost:   Connection succeeded
[0000]  INFO bridge:       mattermost.<team>: joining town-square (ID: town-squaremattermost.<team>)
[0000] DEBUG matterclient: StatusLoop:<nil>
[0000] DEBUG matterclient: WS PING
[0000] DEBUG mattermost:   Choosing login/password based receiving
[0000] DEBUG matterclient: sendWsRequest &model.WebSocketRequest{Seq:1, Action:"ping", Data:map[string]interface {}(nil), Session:model.Session{Id:"", Token:"", CreateAt:0, ExpiresAt:0, LastActivityAt:0, UserId:"", DeviceId:"", Roles:"", IsOAuth:false, Props:model.StringMap(nil), TeamMembers:[]*model.TeamMember(nil)}, T:(i18n.TranslateFunc)(nil), Locale:""}
[0000]  INFO bridge:       mattermost.<team>: joining test (ID: testmattermost.<team>)
[0000] DEBUG matterclient: WsReceiver event: model.WebSocketEvent{Event:"hello", Data:map[string]interface {}{"server_version":"5.0.0.5.0.0-1.963e1365d555e55477abe435a3ed828e.false"}, Broadcast:(*model.WebsocketBroadcast)(0xc42044e6c0), Sequence:0}
[0000]  INFO gateway:      Starting bridge: slack.<team> 
[0000]  INFO slack:        Connecting using webhookurl (sending)
[0000]  INFO slack:        Connecting using token (receiving)
[0000] DEBUG matterclient: WsReceiver response: model.WebSocketResponse{Status:"OK", SeqReply:1, Data:map[string]interface {}{"node_id":"", "server_time":1.5<redacted>e+12, "text":"pong", "version":"5.0.0"}, Error:(*model.AppError)(nil)}
[0000] DEBUG matterclient: WS PONG received
[0000] DEBUG slack:        Choosing token based receiving
[0000] DEBUG slack:        == Receiving event &slack.ConnectingEvent{Attempt:1, ConnectionCount:1}
[0000] DEBUG matterclient: WsReceiver event: model.WebSocketEvent{Event:"status_change", Data:map[string]interface {}{"status":"online", "user_id":"<someuserid>"}, Broadcast:(*model.WebsocketBroadcast)(0xc42049c100), Sequence:1}
[0001] DEBUG slack:        Start listening for Slack messages
[0002]  INFO bridge:       slack.<team>: joining town-square (ID: town-squareslack.<team>)
[0002] DEBUG slack:        == Receiving event &slack.ConnectedEvent{ConnectionCount:1, Info:(*slack.Info)(0xc42066a160)}
[0004] DEBUG slack:        == Receiving event &slack.HelloEvent{}
[0004]  INFO bridge:       slack.<team>: joining test (ID: testslack.<team>)
[0005]  INFO main:         Gateway(s) started succesfully. Now relaying messages
```

**Comment by ArchangeGabriel** [comment]
So, for anyone stumbling upon this, the issue currently lies in `samechannelgateway` not mapping avatars. A workaround is to use standard gateways while the issue is being fixed.

**Comment by ArchangeGabriel** [comment]
@42wim Can you re-open the issue so that it does not slip away?
