### ISSUE TITLE
Whatsapp broken, need sync with upstream

### ISSUE THREAD

**Issue by imShara** [42wim/matterbridge#843]
**Describe the bug**
Whatsapp login fails

**Additional context**
Bacause of https://github.com/Rhymen/go-whatsapp/issues/170

**Comment by 42wim** [comment]
Thanks for reporting, just made a PR #845 with the updates.
You can find the dev binary at https://bintray.com/42wim/nightly/Matterbridge/v1.14.2-33-g32101b2#files
could you test and let me know if this fixed it (don't have whatsapp to test it myself)

Thanks!

**Comment by imShara** [comment]
@42wim, wait a minutes. But I have already tried to make `go get github.com/Rhymen/go-whatsapp@master` on `matterbridge@master` and change line 290 at `whatsapp.go` to `_, err := b.conn.Send(text)`. It works, but thwows `[0349] ERROR whatsapp:     error processing data: received invalid data`

**Comment by 42wim** [comment]
Seems to be also the case in #783 with the previous whatsapp update
It just shows the messages, but the bridge works?

**Comment by imShara** [comment]
@42wim I tried your build. Whatsapp works, whatsapp error throws, xmpp broken https://github.com/42wim/matterbridge/issues/844

>  It just shows the messages, but the bridge works?

Yep

**Comment by 42wim** [comment]
Thanks for the feedback.
I've updated my PR, new build is building which should ignore this error.

**Comment by 42wim** [comment]
Build available here: https://bintray.com/42wim/nightly/Matterbridge/v1.14.2-34-g86e3169#files

**Comment by imShara** [comment]
@42wim XMPP still broken in this build. Why need to check timestamp?

```
[0016] DEBUG xmpp:         == Receiving xmpp.Chat{Remote:"bridged@conference.xxx.xxx/xxx", Type:"groupchat", Text:"xmpp", Subject:"", Thread:"", Ooburl:"", Oobdesc:"", ID:"x-x-x-x-x", ReplaceID:"", Roster:xmpp.Roster(nil), Other:[]string{"", "", ""}, OtherElem:[]xmpp.XMLElement{xmpp.XMLElement{XMLName:xml.Name{Space:"urn:xmpp:mam:tmp", Local:"archived"}, InnerXML:""}, xmpp.XMLElement{XMLName:xml.Name{Space:"urn:xmpp:sid:0", Local:"stanza-id"}, InnerXML:""}, xmpp.XMLElement{XMLName:xml.Name{Space:"urn:xmpp:sid:0", Local:"origin-id"}, InnerXML:""}}, Stamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}
```

**Comment by 42wim** [comment]
That build is a PR build, it doesn't have the xmpp fixes. The xmpp fixes build is in https://bintray.com/42wim/nightly/Matterbridge/v1.14.2-34-g86e3169#files (but that one doesn't have the whatsapp fixes).

But it's going to be merged in master in a few minutes
