### ISSUE TITLE
[WhatsApp] Handle media

### ISSUE THREAD

**Issue by KrzysztofMadejski** [42wim/matterbridge#906]

**Comment by Heath123** [comment]
Um, shouldn't this have a description? At the moment images at least partly work

**Comment by KrzysztofMadejski** [comment]
That's very true. I created it as a more of a technical ticket, looking at what API calls are available and what I didn't yet implement in POC back when starting this.

I'm not using matterbridge anymore, could you elaborate what  "images at least partly work" mean? Let's convert this into a more bussiness ticket as "I want photos incoming from Whatsapp to be shared on other channels" .

**Comment by Heath123** [comment]
OK, so they appear like this:
![image](https://user-images.githubusercontent.com/13787163/92411478-eb3b7f00-f13f-11ea-85e5-c9536aac4b0a.png)
I managed to fix the Someone issue by editing the code (I should PR that) and having no embeds by replacing "jpe" with "jpg" (too hacky to PR, I didn't fix the underlying issue)

**Comment by Heath123** [comment]
After fixes (this is a family chat so I removed the name and picture):
![image](https://user-images.githubusercontent.com/13787163/92411584-5d13c880-f140-11ea-860a-770906c3ee2f.png)

**Comment by 42wim** [comment]
added in #1316

**Comment by furiousjay** [comment]
As far as my setup with version 1.20.0 is concerned, Audio messages from Telegram to Whatsapp are uploaded as .oga files to Whatsapp. Anyway Whatsapp Audio Messages to Telegram are not transmitted at all
![Screenshot_20201209_150613_com whatsapp](https://user-images.githubusercontent.com/38959383/101640030-4aa37680-3a30-11eb-9631-788c78dc261d.jpg)
![Screenshot_20201209_150617_org telegram messenger](https://user-images.githubusercontent.com/38959383/101640035-4bd4a380-3a30-11eb-8b6a-e03d95f6f8fd.jpg)

**Comment by 42wim** [comment]
@furiousjay thanks for reporting.

The telegram issue with .oga should be fixed in master, we now rename .oga files to .ogg.

With the audio issue, could you run matterbridge with `-debug` option?
Then again try sending an audio message from whatsapp to anywhere and paste the debug logs here?
Thanks!

**Comment by rafaelsgirao** [comment]
Hi,
I just updated to the latest release (on linux64) and images bridged from Whatsapp to Discord still appear as ".jpe" files,  like the original issue image [here](https://github.com/42wim/matterbridge/issues/906#issuecomment-688465960) .
Easy reproduction, just send any image on Whatsapp and it'll appear as .jpe on Discord.

**Comment by zeroone82** [comment]
I'll add to this issue.

Audio files sent from Whatsapp -> Mattermost show up in mattermost chat as oga file. Renaming them to ogg would allow for a preview without needing to download the file.

**Comment by furiousjay** [comment]
> @furiousjay thanks for reporting.
> 
> The telegram issue with .oga should be fixed in master, we now rename .oga files to .ogg.
> 
> With the audio issue, could you run matterbridge with `-debug` option?
> Then again try sending an audio message from whatsapp to anywhere and paste the debug logs here?
> Thanks!

I am sorry. I have overseen your question. 
You are right: The issue is now fixed. Voice Messages from Whatsapp to Telegram are now integrated as playable Voice Messages in Telegram Groups. That's very nice! 
Also I can confirm that Telegram Voice Messages are now .ogg files in Whatsapp. That's great, but still it would be even better if the files were playable in Whatsapp without third party apps.

Anyway thank you so much for your work. Matterbridge is just amazing.

**Comment by zeroone82** [comment]
> @furiousjay thanks for reporting.
> 
> The telegram issue with .oga should be fixed in master, we now rename .oga files to .ogg.
> 

Would it be possible to implement the same change to the mattermost handler? That would make audio files playables inside a browser and the desktop app.
